import type { SupportedLanguage } from '@/lib/translations';
import type { TemplateId } from '@/components/biodata/TemplateRegistry';

export interface CommunityField { name: string; explanation: string }
export interface CommunityPageData {
  slug: string; path: string; updatedAt: string; lang: SupportedLanguage; name: string; nativeName: string;
  title: string; description: string; template: TemplateId; intro: string;
  sections: Array<{ heading: string; paragraphs: string[] }>;
  fields: CommunityField[]; faqs: Array<{ question: string; answer: string }>;
  related: Array<{ href: string; label: string }>;
}

export const COMMUNITY_PAGES: CommunityPageData[] = [
{
 slug:'gujarati', path:'/gujarati-marriage-biodata', updatedAt:'2026-10-08', lang:'gu', name:'Gujarati', nativeName:'ગુજરાતી',
 title:'Gujarati Marriage Biodata Format | EasyBiodataMaker',
 description:'Create a Gujarati marriage biodata with practical guidance for family, education, career, lineage and privacy fields. No login required.', template:'midnight-gold',
 intro:'A useful Gujarati marriage biodata should make family background easy to understand without turning every tradition into a mandatory field. Include the details your family actually uses when discussing a match, and leave sensitive information out of a copy that will circulate widely.',
 sections:[
 {heading:'Start with roots, then add the present', paragraphs:[
 'For many Gujarati families, the ancestral village or family place can provide useful context. A person may live in Ahmedabad, Surat, Vadodara, Mumbai or overseas while still identifying strongly with a family village. If gam or native place is meaningful to your family, put it in the family section rather than hiding it in a paragraph.',
 'Gotra can also be relevant for Hindu families. Gujarati families are diverse, so the biodata should not assume that every household follows the same matching practice. If your family checks gotra, enter it clearly. If your family does not use it, simply leave the optional field off. The same principle applies to community or sub-community: state only what the family considers useful and accurate.' ]},
 {heading:'Make education and work easy to scan', paragraphs:[
 'Gujarati matrimonial conversations often move quickly from education to career and business. Give the highest qualification, field of study, college or university, occupation, designation and work location as separate rows. For a family business, a short description such as “textile trading, Surat” is more informative than the generic label “business”. Avoid inflated claims about income or assets; the biodata is an introduction, not a financial statement.',
 'For an NRI candidate, add the country and city and clearly state whether the person is a citizen, permanent resident or on a temporary visa. Do not publish passport numbers, visa numbers or employer-sensitive information.' ]},
 {heading:'Share the document thoughtfully', paragraphs:[
 'A biodata is often forwarded through family WhatsApp groups, relatives and community contacts. Use a separate contact number if possible, and consider hiding the full home address from the first version. A city and state are usually enough until both families agree to continue the conversation.',
 'Use a current, respectful portrait and avoid uploading more photos than necessary. A profile photo plus one or two additional photos is enough for a first introduction. Keep the PDF focused on useful information rather than adding social-media handles or personal identifiers.' ]},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing, check that the Gujarati and English labels say the same thing and that the family names are spelled consistently. If an elder will read the document, a clear Gujarati heading can be more useful than decorative Gujarati copy. Keep the profile photograph current and avoid a collage on the first page.', 'A common mistake is treating a community field as a fact that must apply to everyone. Gam, gotra, sub-community and kuldevi can be meaningful, but the right answer is the one your family confirms. Another mistake is publishing too much NRI information. Country, city and broad status are useful; passport and visa identifiers are not.', 'Before sending the final PDF, open it on a phone and check that names, dates and numbers are readable without zooming excessively. If contact details are hidden, make sure the family knows which person should receive replies. A good Gujarati biodata is specific enough for a serious introduction and restrained enough to be safe when forwarded.', 'If the family uses a separate horoscope or other document, say so instead of repeating technical details in the biodata. This keeps the first file practical for relatives who only need the basic profile. For a Gujarati family, also check that the final version distinguishes the candidate’s current city from the ancestral place and that business information is described plainly. If an overseas family is involved, agree on whether income should be shown before publishing. The safest version is the one both the candidate and parents are comfortable forwarding.']},
 ],
 fields:[
 {name:'Gam / ancestral place', explanation:'Use this only when your family considers the ancestral village or town relevant.'},
 {name:'Gotra', explanation:'Useful for families who include lineage information in matrimonial discussions; optional otherwise.'},
 {name:'Kuldevi / family tradition', explanation:'Add the family term your household actually uses; terminology can vary by community.'},
 {name:'Community or sub-community', explanation:'State the family identity accurately without assuming it applies to every Gujarati household.'},
 {name:'NRI status', explanation:'For overseas candidates, country, city and broad residency status are more useful than document numbers.'},
 ],
 faqs:[
 {question:'What should a Gujarati marriage biodata include?',answer:'Start with personal details, family background, education and career, optional lineage details, expectations and a safe way to contact the family. Add gam or gotra only when relevant to your family.'},
 {question:'Should I include gam and gotra?',answer:'If your family normally discusses these details during matching, yes. Both are optional in a modern biodata, so do not add them just because another family uses them.'},
 {question:'What should an NRI Gujarati biodata mention?',answer:'Country, city, broad residency or citizenship status, occupation, work location and relocation expectations are useful. Avoid passport or visa numbers.'},
 {question:'How many photos should I add?',answer:'One profile photo and up to two additional photos keeps the document focused and easy to share.'},
 ],
 related:[{href:'/marathi-marriage-biodata',label:'Marathi biodata format'},{href:'/hindi-marriage-biodata',label:'Hindi biodata format'},{href:'/jain-marriage-biodata',label:'Jain marriage biodata'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'marathi', path:'/marathi-marriage-biodata', updatedAt:'2026-10-08', lang:'mr', name:'Marathi', nativeName:'मराठी',
 title:'Marathi Marriage Biodata Format | EasyBiodataMaker',
 description:'Create a Marathi marriage biodata with practical guidance for family roots, kuldaivat, education, career, expectations and safe sharing.', template:'rajwada-crimson',
 intro:'A Marathi marriage biodata works best when it separates traditional family information from practical details about education, work and expectations. The format should be readable to parents and relatives while still feeling current for the person getting married.',
 sections:[
 {heading:'Family roots and lineage', paragraphs:[
 'Many Maharashtrian families include a native village or mool gaon even when the family now lives in Mumbai, Pune, Nashik, Nagpur or another city. Add it when it genuinely helps identify family roots. Kuldaivat may also be meaningful, but it is not a universal matching requirement, so keep it optional.',
 'Gotra and pravar can matter in some Brahmin families. Because practices differ between Konkanastha, Deshastha, Karhade, Saraswat and other communities, do not invent a pravar if you do not know it. Ask an elder or family source and use the exact spelling your family uses.' ]},
 {heading:'Career details should be precise', paragraphs:[
 'A strong Marathi biodata makes education and employment easy to scan. Separate qualification, field, college, occupation, designation and city. For government or public-sector roles, the department and designation can be useful. For private employment, naming the role and work location is normally enough; you do not need to publish confidential employer details.',
 'Income is optional. If included, use a broad annual figure rather than attaching salary slips or tax documents. The purpose of the biodata is to help families decide whether to continue a conversation, not to disclose financial records.' ]},
 {heading:'Traditional information should remain optional', paragraphs:[
 'Fields such as kuldaivat, gotra, pravar or family status can be useful when the household expects them. They should not crowd out personality, education or career. A clean format lets a family see the information they care about without forcing everyone into one definition of a Marathi marriage match.',
 'For sharing, keep the first version conservative. City and state are usually sufficient for an initial introduction. A phone number can be included when the family is comfortable; a full residential address can wait until there is a reason to exchange it.' ]},
 {heading:'Final checklist before sharing', paragraphs:['Before finalising a Marathi biodata, ask one family member to verify traditional terms such as mool gaon, kuldaivat, gotra and pravar. These details are easy to mistype and can be sensitive to the family. The modern sections should still remain prominent: education, occupation, work city, hobbies and expectations.', 'Avoid copying a biodata from another family and replacing only the name. That approach often carries fields that are irrelevant or inaccurate. Another common mistake is writing a long description of family status instead of giving useful facts. Parents\' occupations, siblings and native place are enough for most first introductions.', 'For sharing, keep a clean PDF version and a version with less contact information if the family expects broad forwarding. Check Marathi text on a phone before sending. If the person works abroad, add country and city but do not publish visa numbers. The best format is one an elder can understand quickly and the candidate is comfortable sharing.', 'If a horoscope or family document is exchanged separately, keep the biodata focused on the person and family. This makes the PDF easier to read and easier to update when a job or city changes. For a Marathi family, also check that the person’s current city is separate from mool gaon and that traditional fields have been verified. If the family expects a separate horoscope, keep that file separate. This makes the main biodata easier to update after a job change, relocation or new qualification.']},
 ],
 fields:[
 {name:'Mool gaon / native place', explanation:'Useful for recording ancestral roots when the family considers them relevant.'},
 {name:'Kuldaivat', explanation:'Family deity information can be included when it is part of your household tradition.'},
 {name:'Gotra', explanation:'Commonly requested by some families; verify the family spelling before publishing.'},
 {name:'Pravar', explanation:'Relevant to some Brahmin families; do not guess it if the family does not know it.'},
 {name:'Family type', explanation:'Nuclear, joint or another accurate description can help set expectations.'},
 ],
 faqs:[
 {question:'Is kuldaivat required in a Marathi biodata?',answer:'No. It is useful for families who consider it part of their matrimonial introduction, but it should remain optional.'},
 {question:'Should Brahmin families include gotra and pravar?',answer:'If the family normally uses them for matching, include both after verifying them with an elder or trusted family source.'},
 {question:'Should I include salary?',answer:'You can include a broad annual income if your family is comfortable. Do not attach salary slips or financial documents.'},
 {question:'What is a good photo style?',answer:'Use a recent, clear portrait with simple clothing and good lighting. The biodata should remain the focus.'},
 ],
 related:[{href:'/gujarati-marriage-biodata',label:'Gujarati biodata format'},{href:'/hindi-marriage-biodata',label:'Hindi biodata format'},{href:'/biodata-for-marriage-boy',label:'Biodata for marriage boy'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'hindi', path:'/hindi-marriage-biodata', updatedAt:'2026-10-08', lang:'hi', name:'Hindi', nativeName:'हिंदी',
 title:'Hindi Marriage Biodata Format | EasyBiodataMaker', description:'Create a Hindi marriage biodata with practical guidance for family, education, career, expectations and privacy. No login required.', template:'haldi-marigold',
 intro:'A Hindi marriage biodata is often shared across relatives who want the important facts quickly. A useful format keeps personal, family, education and career details separate, while leaving culturally specific fields optional so each family can decide what belongs.',
 sections:[
 {heading:'Keep the family section factual', paragraphs:['For families in North and Central India, the family section can include parents, siblings, native place and a short description of family background. If caste, sub-caste, gotra or other lineage information is part of your family’s normal matrimonial process, add it as an optional field rather than assuming it applies to everyone.','Native place can be particularly useful when a family has moved to a different city. Write the village, town or district clearly and avoid long family-history paragraphs that make the biodata hard to scan.']},
 {heading:'Education and career should read like a profile', paragraphs:['List the highest qualification first, followed by field of study, institution, occupation and designation. If the person is self-employed, describe the work in one accurate line. If they work in a company, the role and work city are usually enough for an introduction.','Expectations should be specific but respectful. Instead of a long checklist of demands, describe the qualities, location preferences and broad life goals that matter to the person.']},
 {heading:'Protect information when forwarding', paragraphs:['Because Hindi biodatas are frequently forwarded through several family contacts, avoid publishing Aadhaar numbers, passport details, exact workplace addresses or other documents. A city, state and one family contact number are generally sufficient for an initial exchange.','Use a current portrait and keep additional photos limited. The document should remain readable on a phone because many relatives will view it through WhatsApp rather than on a desktop.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sending a Hindi biodata, read it once as a relative who has never met the person. Are the education, occupation, family and location facts easy to find? If not, shorten paragraphs and use rows. Hindi headings can be combined with English values when the candidate works in an English-speaking environment.', 'Avoid overloading the profile with caste, community or horoscope fields simply because another family uses them. They are optional and should reflect the actual matching process of the household. Also avoid vague claims such as “very cultured” or “high-status family” when a factual description would be clearer.', 'A privacy check is especially useful before WhatsApp forwarding. Remove identity numbers, exact home addresses and document scans. Confirm that the phone number belongs to the person or family member who is ready to receive calls. Finally, view the PDF on a 390px-wide phone; if the table becomes difficult to read, choose a more spacious template.', 'If a horoscope or additional family document is shared separately, keep technical details out of the main profile. This also makes it easier to create a new version when the candidate changes jobs or cities. For a Hindi-speaking family, also check whether the document should be bilingual. A Hindi heading with English professional terms can be easier for a mixed-generation family than translating every employer or qualification name. Keep the candidate’s own voice in the about section and avoid turning the profile into a family advertisement.']},
 ],
 fields:[{name:'Native place',explanation:'Record the family’s village, town or district when it helps explain roots.'},{name:'Gotra',explanation:'Include when your family uses lineage information for matrimonial discussions.'},{name:'Caste / sub-caste',explanation:'Optional; use the family’s preferred terminology and do not assume it applies universally.'},{name:'Family background',explanation:'A short factual description is more useful than a long genealogy.'},{name:'Relocation preference',explanation:'Useful when location after marriage is an important family expectation.'}],
 faqs:[{question:'What should a Hindi marriage biodata contain?',answer:'Personal details, family background, education, career, optional community fields, expectations and a safe contact method are the core sections.'},{question:'Should caste and gotra be included?',answer:'Only if they are relevant to your family’s matching process. Both can be optional.'},{question:'How should expectations be written?',answer:'Keep them respectful and focused on values, location and broad life goals rather than a long list of demands.'},{question:'Can I make a Hindi biodata without login?',answer:'Yes. The builder is designed for no-login use and stores the draft locally in the browser.'}],
 related:[{href:'/biodata-for-marriage-girl',label:'Biodata for marriage girl'},{href:'/biodata-for-marriage-boy',label:'Biodata for marriage boy'},{href:'/marathi-marriage-biodata',label:'Marathi biodata format'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'punjabi', path:'/punjabi-marriage-biodata', updatedAt:'2026-10-08', lang:'pa', name:'Punjabi', nativeName:'ਪੰਜਾਬੀ', title:'Punjabi Marriage Biodata Format | EasyBiodataMaker', description:'Create a Punjabi marriage biodata with clear family, education, career and optional community details, designed for easy sharing.', template:'royal-peacock',
 intro:'A Punjabi marriage biodata should feel confident and clear without becoming a catalogue of family status. Put the person first, then give enough family and community context for relatives to understand the match.',
 sections:[
 {heading:'Personal profile first', paragraphs:['Start with the person’s name, date and place of birth, height, education and occupation. If religion or community details are important to the family, keep them in a separate section so the reader can distinguish personal facts from family background.','For Sikh families, religious practice or ceremony preferences may matter to some households. Do not assume one level of observance; describe the family’s own position accurately and respectfully.']},
 {heading:'Family information without exaggeration', paragraphs:['Parents’ names and occupations, siblings and native place are useful. If the family has a business, describe its sector and location rather than using broad claims about status. A simple line is easier for relatives to understand and easier to update later.','For diaspora families, country and city can be more useful than a vague “settled abroad”. Add residency status only at a broad level and never publish passport or immigration document numbers.']},
 {heading:'Sharing through family networks', paragraphs:['Punjabi biodatas often travel quickly through relatives and community contacts. Keep the first version phone-friendly, with one clear profile image and only a few additional photos. If you do not want your home address forwarded, show only city and state and provide a family contact number instead.','A good biodata is a conversation starter. Avoid public social handles, identity numbers and employer-sensitive information.']},
 {heading:'Final checklist before sharing', paragraphs:['Before a Punjabi biodata is circulated, confirm that names, family relationships and religious details are written exactly as the family prefers. If the household uses Punjabi script for headings, make sure the chosen template remains readable for relatives who use English as their main working language.', 'Avoid turning family background into a status statement. A clear occupation, education, business sector or professional role is more useful than phrases about being “well settled” without context. Similarly, do not assume that every Sikh or Punjabi family follows the same ceremony, religious or community practice.', 'For diaspora candidates, check the time-zone and contact expectation before publishing a phone number. A city and country are enough for the first copy. If the person prefers WhatsApp, say so in a simple way rather than publishing several contact channels. Keep the first document easy to forward and reserve detailed personal information for a later conversation.', 'If the family shares additional documents later, keep them separate from the first biodata. The introductory file should remain easy to understand, forward and revoke if the conversation does not continue. For Punjabi families, also check whether the document should use Punjabi, English or both. Keep names and religious terms consistent across scripts. If relatives are in different countries, agree on the preferred contact channel and time before sharing a personal number.']},
 ],
 fields:[{name:'Native place',explanation:'Useful when the family has roots in a particular town or village.'},{name:'Religion / community',explanation:'State the family’s identity in the terminology they use.'},{name:'Amritdhari / religious practice',explanation:'Include only when it is genuinely relevant to the family; practices vary.'},{name:'Country and city',explanation:'Important for candidates living outside India.'},{name:'Relocation preference',explanation:'Useful when the post-marriage location is a key expectation.'}],
 faqs:[{question:'What makes a Punjabi biodata easy to share?',answer:'Clear headings, short rows, a good portrait, readable phone formatting and a small amount of family context make it easier for relatives to forward and discuss.'},{question:'Should Sikh religious details be mandatory?',answer:'No. Include only the details your family considers relevant, and describe them accurately.'},{question:'Should an overseas candidate include visa details?',answer:'A broad residency or citizenship status can be useful. Avoid publishing document numbers.'},{question:'How many photos are enough?',answer:'One profile photo plus up to two additional photos is usually sufficient for an introductory biodata.'}],
 related:[{href:'/sikh-marriage-biodata',label:'Sikh marriage biodata'},{href:'/hindi-marriage-biodata',label:'Hindi biodata format'},{href:'/biodata-for-marriage-boy',label:'Biodata for marriage boy'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'tamil', path:'/tamil-marriage-biodata', updatedAt:'2026-10-08', lang:'ta', name:'Tamil', nativeName:'தமிழ்', title:'Tamil Marriage Biodata Format | EasyBiodataMaker', description:'Create a Tamil marriage biodata with practical family, education, career and horoscope-related field guidance and privacy tips.', template:'kanjivaram-temple',
 intro:'A Tamil marriage biodata often combines concise personal information with family and traditional matching details. The best format makes optional cultural fields easy to include without making them mandatory for every household.',
 sections:[
 {heading:'Personal and family details', paragraphs:['Begin with the person’s education, occupation, place of birth and family details. Parents’ names, occupations and native place help relatives understand the family context. Keep the first page easy to scan on a phone.','Some families also exchange horoscope-related information separately. If your household wants a field for it, add the exact detail your family uses rather than copying terminology from another community.']},
 {heading:'Career and location matter', paragraphs:['Tamil families may be comparing candidates living in Chennai, Coimbatore, Bengaluru, Hyderabad, the United States, Singapore or elsewhere. State the current work location and occupation clearly. For a person working abroad, country and city are useful context and can be paired with a broad residency status.','Do not include confidential employer information. A role, industry and city are generally enough for an introductory biodata.']},
 {heading:'Privacy for forwarded biodatas', paragraphs:['A biodata can reach people outside the intended family group. Avoid Aadhaar, passport, exact house numbers, visa numbers and financial documents. If contact privacy matters, show a family contact number and city rather than a full address.','Use a recent portrait and keep the additional gallery small. A clean Tamil heading with English or Tamil field values can be easier for mixed-language families than a page packed with decorative text.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing a Tamil biodata, verify the spelling of names in Tamil and English if both are used. Birth information, family details and any traditional matching fields should come from the family’s own records rather than a copied template. If a horoscope is shared separately, there is no need to crowd the biodata with technical details.', 'Avoid assuming that one Tamil family’s community or ritual practices apply to another. A good page uses optional fields and lets the family decide. Career information should be equally practical: degree, specialization, occupation, designation and city give a prospective family a much clearer picture than a long paragraph.', 'For privacy, remove exact house numbers and document identifiers before forwarding. Check the final Tamil PDF on both Android and desktop because font rendering can look different. If the candidate is overseas, state the current city and country and explain relocation expectations in one sentence rather than a complicated list.', 'If the family normally exchanges a separate horoscope or family profile, keep those documents separate from the introductory biodata. This reduces clutter and makes privacy easier to manage. For Tamil families, also check that the template leaves enough space for longer Tamil labels. If the candidate works abroad, keep current residence and future relocation preference separate. This prevents a reader from assuming that the current overseas city automatically means permanent settlement.']},
 ],
 fields:[{name:'Native place',explanation:'Useful for recording family roots when it is relevant.'},{name:'Birth details',explanation:'Some families exchange detailed birth information for traditional matching; include only what you choose to share.'},{name:'Community / family tradition',explanation:'Use the family’s own terminology rather than assuming one practice.'},{name:'Work location',explanation:'Helps families understand where the candidate currently lives and works.'},{name:'Overseas status',explanation:'Country, city and broad status are useful for candidates abroad.'}],
 faqs:[{question:'Should horoscope information be on the biodata?',answer:'It can be included when your family uses it, but it can also be kept separate. The builder allows optional fields so the document can stay concise.'},{question:'Can I create the biodata in Tamil?',answer:'Yes. The template system supports Tamil labels and typography while keeping user-entered values unchanged.'},{question:'What should an NRI Tamil biodata include?',answer:'Country, city, occupation, broad residency status and relocation expectations are useful additions.'},{question:'What should I avoid sharing?',answer:'Avoid identity numbers, passport or visa numbers, exact home addresses and financial documents.'}],
 related:[{href:'/telugu-marriage-biodata',label:'Telugu biodata format'},{href:'/kannada-marriage-biodata',label:'Kannada biodata format'},{href:'/hindi-marriage-biodata',label:'Hindi biodata format'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'telugu', path:'/telugu-marriage-biodata', updatedAt:'2026-10-08', lang:'te', name:'Telugu', nativeName:'తెలుగు', title:'Telugu Marriage Biodata Format | EasyBiodataMaker', description:'Create a Telugu marriage biodata with practical guidance for family roots, education, career, expectations and safe sharing.', template:'kanjivaram-temple',
 intro:'A Telugu marriage biodata should give parents and relatives enough context to discuss a match while keeping the document compact. Family roots, education, occupation and location usually deserve the clearest treatment.',
 sections:[
 {heading:'Build the profile around the person', paragraphs:['Start with name, birth details, education, occupation and current location. Family details should support the profile rather than overwhelm it. If the family uses community or lineage information, place it in optional rows and use the exact terminology your elders use.','Do not fill a traditional field just because a sample biodata contains it. A field that is wrong or guessed can create more confusion than leaving it blank.']},
 {heading:'Career and family context', paragraphs:['For software, medicine, engineering, business and other professional careers, use a precise designation and work city. If the candidate is self-employed, describe the sector in plain language. For overseas candidates, add country and city and a broad residency status.','Family information can include parents, siblings and native place. Keep descriptions factual; avoid claims about status, wealth or social standing that cannot be verified.']},
 {heading:'Keep sharing private', paragraphs:['Many family introductions happen through WhatsApp. A first biodata should therefore avoid identity numbers, exact house addresses and immigration document details. A family phone number and city are usually enough until both sides decide to speak directly.','One profile photo and a couple of additional images are sufficient. The document should remain legible on a small screen and should not depend on people zooming into decorative graphics.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing a Telugu biodata, ask an elder to verify any family-specific traditional fields and the spelling of the person’s name in Telugu. A clean separation between personal facts and family traditions makes the document easier for both generations to use.', 'Avoid filling every available field. Empty optional fields are better than guessed information, especially for lineage or birth details. Do not turn the career section into a financial profile either; a role, organization type, designation and location are generally sufficient.', 'For candidates outside India, state the country and city and describe broad residency status if it matters. Avoid passport and visa numbers. Before forwarding, open the PDF on a phone, check the photo crop, and confirm that the contact number is the one the family actually wants to share. This simple review prevents many avoidable privacy mistakes.', 'If detailed traditional matching information is normally exchanged separately, do not duplicate it in the main biodata. A concise first document is easier to review and less likely to expose information unnecessarily. For Telugu families, also check that native place and current residence are separate. If a family uses traditional birth information, verify it before publication. A modern biodata should still make the candidate’s education, occupation and personality easy to understand at a glance.']},
 ],
 fields:[{name:'Native place',explanation:'Use for family roots when the household considers it relevant.'},{name:'Family / community details',explanation:'Use the family’s preferred terminology and keep it optional.'},{name:'Birth details',explanation:'Include the level of detail the family is comfortable sharing.'},{name:'Work location',explanation:'Useful for candidates working in another Indian city or overseas.'},{name:'Relocation expectation',explanation:'Clarifies broad location preferences after marriage.'}],
 faqs:[{question:'What are the main sections in a Telugu biodata?',answer:'Personal details, family, education and career, about/expectations, photos and a safe contact method are the practical core.'},{question:'Should traditional matching fields be included?',answer:'Only when your family uses them. Keep them optional and verify the terminology with an elder.'},{question:'How should an overseas candidate be described?',answer:'Country, city, occupation and broad residency status are useful; do not publish document numbers.'},{question:'Can I keep contact details private?',answer:'Yes. The builder supports hiding contact details from the final document.'}],
 related:[{href:'/tamil-marriage-biodata',label:'Tamil biodata format'},{href:'/kannada-marriage-biodata',label:'Kannada biodata format'},{href:'/hindi-marriage-biodata',label:'Hindi biodata format'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'bengali', path:'/bengali-marriage-biodata', updatedAt:'2026-10-08', lang:'bn', name:'Bengali', nativeName:'বাংলা', title:'Bengali Marriage Biodata Format | EasyBiodataMaker', description:'Create a Bengali marriage biodata with clear family, education, career and optional cultural details, built for private sharing.', template:'pearl-lavender',
 intro:'A Bengali marriage biodata should balance personal identity, family context and practical career information. A calm, readable format works especially well when the document is viewed by several relatives on phones.',
 sections:[
 {heading:'Family information should be concise', paragraphs:['Parents’ names and occupations, siblings, family location and native place are useful starting points. If the family wants to include lineage or community information, make it a clearly labelled optional row. Do not assume that one Bengali household follows the same matching customs as another.','Education is often one of the first sections relatives scan. Give the highest qualification, field and institution clearly, followed by occupation, designation and work location.']},
 {heading:'Describe personality without making claims', paragraphs:['The about section is a good place for a short description of interests, lifestyle and values. Avoid generic phrases such as “simple and cultured” unless you explain what they mean for this person. Hobbies, languages and expectations can make the profile more useful.','If the person lives outside West Bengal or outside India, state the current city and country clearly. Relocation expectations can be a separate sentence rather than a long demand list.']},
 {heading:'Privacy-first sharing', paragraphs:['Before forwarding the biodata, remove identity numbers, exact home address, passport information and financial documents. If contact privacy matters, show a family contact number and city instead of a full residential address.','A current portrait and one or two additional photos are enough. Keep the file light and readable so it can be opened quickly from a messaging app.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing a Bengali biodata, check whether the family wants Bengali headings, English headings or a combination. The person’s name, education and occupation should be easy to find in either case. Any community or lineage detail should be confirmed by the family rather than copied from an online sample.', 'Avoid generic personality claims and long family histories. A short description of interests, values and expectations gives a reader something concrete to discuss. Similarly, do not make a person’s location sound more settled than it is; current city and country are enough to establish context.', 'For privacy, prepare the first biodata as a shareable introduction rather than a complete identity record. Leave out government IDs, exact home addresses and document images. Check the final file on a small phone screen, because a beautiful desktop layout can become difficult to read when forwarded through messaging apps.', 'If the family has a separate horoscope or extended family profile, keep it outside the introductory biodata. The main document should answer the first practical questions without becoming a personal archive. For Bengali families, also check that education and current location are prominent enough for relatives to scan quickly. If the candidate has moved abroad, describe the present situation accurately without promising future immigration or settlement outcomes.']},
 ],
 fields:[{name:'Native place',explanation:'Useful for recording family roots when it matters to the household.'},{name:'Community / lineage',explanation:'Include only the family identity information you actually use.'},{name:'Education details',explanation:'List qualification, subject and institution in a simple sequence.'},{name:'Current city',explanation:'Important when the person has moved for education or work.'},{name:'Relocation preference',explanation:'Useful when location after marriage is a meaningful expectation.'}],
 faqs:[{question:'What should a Bengali biodata focus on?',answer:'A clear personal profile, family background, education, career, values and a safe contact method form a strong base.'},{question:'Should I add community or lineage details?',answer:'Only if your family considers them relevant. They should remain optional.'},{question:'How long should the about section be?',answer:'A short paragraph is usually enough. Focus on personality, interests and values that help someone start a conversation.'},{question:'Can the biodata be shared privately?',answer:'Yes. Keep the first version limited to information you are comfortable forwarding through relatives.'}],
 related:[{href:'/hindi-marriage-biodata',label:'Hindi biodata format'},{href:'/marathi-marriage-biodata',label:'Marathi biodata format'},{href:'/christian-marriage-biodata',label:'Christian marriage biodata'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'kannada', path:'/kannada-marriage-biodata', updatedAt:'2026-10-08', lang:'kn', name:'Kannada', nativeName:'ಕನ್ನಡ', title:'Kannada Marriage Biodata Format | EasyBiodataMaker', description:'Create a Kannada marriage biodata with practical family, education, career and privacy guidance for modern and traditional families.', template:'emerald-palace',
 intro:'A Kannada marriage biodata can be traditional in its family context while remaining modern in presentation. The key is to make the information easy to scan and to treat community-specific fields as optional.',
 sections:[
 {heading:'Roots and family context', paragraphs:['Native place, parents and siblings give relatives a quick sense of family background. For families that use lineage, community or traditional matching details, add those rows only after confirming them with the family. Karnataka contains many distinct communities, so a generic “traditional field list” is not appropriate for everyone.','If the family has moved between Bengaluru, Mysuru, Hubballi, Mangaluru or another city, the ancestral place can be shown separately from the current location.']},
 {heading:'Education and career', paragraphs:['Karnataka has a large professional and technology workforce, so the career section should be precise. Write the degree, specialization, employer or work type, designation and work city. For a founder or business owner, name the sector and location rather than making a broad claim about business size.','For candidates abroad, country, city and broad residency status help families understand the practical situation. Relocation expectations should be stated in plain language.']},
 {heading:'Respectful privacy', paragraphs:['A first biodata should not contain Aadhaar numbers, passport details, visa numbers, exact house addresses or copies of documents. These details can be exchanged later if necessary.','Choose a clear profile portrait and a small additional gallery. Since many families will open the file on a phone, use short rows and avoid decorative layouts that reduce text size.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sending a Kannada biodata, verify Kannada names and family terminology with the person or an elder. Karnataka has many communities and family traditions, so a generic online field list can easily become inaccurate. Keep optional fields clearly optional.', 'Avoid mixing ancestral place and current residence into one row. A family may have roots in one district while the candidate works in Bengaluru or abroad. Showing both separately gives a much clearer picture. The same applies to career: qualification, specialization, designation and location are more useful than broad claims about success.', 'For privacy, do a final forwarding check. Remove identity numbers, exact home addresses and immigration documents. If the candidate is overseas, country and city plus broad residency status are enough for the first conversation. Open the PDF on a phone and verify that Kannada characters remain legible and that no row has been clipped.', 'If traditional matching documents are exchanged separately, keep the biodata concise and reference them only when necessary. This helps the candidate control which information is shared with each family. For Kannada families, also check that the current city, native place and work location are not accidentally combined. If the candidate is a technology professional, keep the job title understandable to relatives outside the industry rather than filling the biodata with internal corporate terms.']},
 ],
 fields:[{name:'Native place',explanation:'Separates ancestral roots from the current city.'},{name:'Community / family tradition',explanation:'Use only terminology confirmed by the family.'},{name:'Birth details',explanation:'Include only the level of detail the family wishes to share.'},{name:'Work location',explanation:'Especially useful for Bengaluru and overseas professionals.'},{name:'Relocation expectation',explanation:'Makes post-marriage location preferences clear.'}],
 faqs:[{question:'Should Kannada biodatas include community details?',answer:'They can, but the field should be optional because practices vary across Karnataka communities.'},{question:'What career information is useful?',answer:'Qualification, specialization, occupation, designation and work location are usually enough for an introduction.'},{question:'Should an NRI candidate include visa numbers?',answer:'No. A broad residency or citizenship status is sufficient for a first biodata.'},{question:'Can I use Kannada headings with English values?',answer:'Yes. This can work well for families who read Kannada while the candidate normally uses English at work.'}],
 related:[{href:'/telugu-marriage-biodata',label:'Telugu biodata format'},{href:'/tamil-marriage-biodata',label:'Tamil biodata format'},{href:'/bengali-marriage-biodata',label:'Bengali biodata format'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'rajasthani', path:'/rajasthani-marriage-biodata', updatedAt:'2026-10-08', lang:'hi', name:'Rajasthani', nativeName:'राजस्थानी / हिन्दी', title:'Rajasthani Marriage Biodata Format | EasyBiodataMaker', description:'Create a Rajasthani marriage biodata with practical guidance for family roots, community context, education, business and privacy.', template:'sandstone-rajasthan',
 intro:'Rajasthani matrimonial introductions can cross regional, business and community networks. A useful biodata should therefore distinguish ancestral roots, current city, community identity and career information rather than combining everything into one paragraph.',
 sections:[
 {heading:'Separate region, community and family identity', paragraphs:['“Rajasthani” can describe regional roots while a family may also identify with a specific community or religious tradition. Keep those concepts separate. If your family uses a community, gotra or lineage field, enter the exact information your family recognizes rather than selecting a label because it appears in an online sample.','Ancestral town or village can be useful even when the family now lives in Jaipur, Delhi, Mumbai, Ahmedabad or overseas. Put the ancestral place in the family section and the current location in the career/contact section.']},
 {heading:'Business and professional information', paragraphs:['For business families, describe the business sector and location in one or two lines. A family-owned enterprise, professional practice or corporate career can all be presented clearly without publishing turnover, tax records or confidential company information.','Education, occupation and designation should be separate rows. If the candidate is abroad, country, city and broad residency status provide more useful context than a generic “NRI” label.']},
 {heading:'Privacy when the network is large', paragraphs:['Rajasthani family networks can be broad, so the first biodata should be designed for forwarding. Avoid identity numbers, exact home addresses and document scans. A city, state and family contact are enough until the conversation becomes more private.','Use a current portrait and a small photo set. A premium design can look traditional without filling every inch with motifs; readability matters more when older relatives view the biodata on a phone.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing a Rajasthani biodata, confirm whether the family wants to identify itself by regional roots, community, religion or a combination. Those categories are not interchangeable. Use the exact family terminology and avoid turning an ancestral town into a statement about social status.', 'A common mistake in business families is publishing too much financial detail. The biodata should say what the person does and where they work; it does not need tax returns, turnover documents or property lists. For professionals, a clear designation and location are enough.', 'Because family networks can be wide, create a first version that is safe to forward. Use city and state instead of an exact address, and a family contact rather than several personal numbers. Review the final PDF on a phone and make sure the decorative block-print border does not reduce text size. Traditional design should support the information, not compete with it.', 'If the family normally exchanges a detailed family profile separately, keep the first biodata concise. This is especially useful when relatives forward the file beyond the original recipient. For Rajasthani families, also check that regional roots, community identity and current residence remain separate. If the family has a business, describe its field and location without publishing private financial records. This gives relatives useful context without turning the biodata into a status document.']},
 ],
 fields:[{name:'Ancestral place',explanation:'Records the family’s regional roots separately from current residence.'},{name:'Community identity',explanation:'Use the family’s own preferred terminology; regional identity and community are not always the same.'},{name:'Gotra / lineage',explanation:'Optional and should be entered only when the family knows the correct information.'},{name:'Business / occupation',explanation:'Describe sector, role and location without publishing confidential financial documents.'},{name:'NRI status',explanation:'Country, city and broad residency status are useful for overseas candidates.'}],
 faqs:[{question:'Is Rajasthani a community field?',answer:'It can describe regional roots, while a family may also use a separate community or religious identity. Keep those concepts distinct.'},{question:'Should a business family publish turnover?',answer:'No. A short description of the business sector and location is usually enough for a first biodata.'},{question:'Should gotra be mandatory?',answer:'No. Include it only when your family uses it and the information is verified.'},{question:'What privacy details should I avoid?',answer:'Avoid identity numbers, document scans, exact home addresses and confidential financial information.'}],
 related:[{href:'/hindi-marriage-biodata',label:'Hindi biodata format'},{href:'/jain-marriage-biodata',label:'Jain marriage biodata'},{href:'/gujarati-marriage-biodata',label:'Gujarati biodata format'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'jain', path:'/jain-marriage-biodata', updatedAt:'2026-10-08', lang:'en', name:'Jain', nativeName:'Jain', title:'Jain Marriage Biodata Format | EasyBiodataMaker', description:'Create a Jain marriage biodata with optional sect, family and lineage fields, practical guidance and privacy-first sharing.', template:'sapphire-silver',
 intro:'Jain families can have different matrimonial traditions, so a good biodata should let the family choose the details that matter instead of assuming one checklist fits everyone. Keep religious or community fields precise and optional.',
 sections:[
 {heading:'Use the family’s own Jain terminology', paragraphs:['Jain matrimonial introductions may include information about the family’s tradition or sect, but practices differ between households. If a family identifies with Shvetambara, Digambara or a particular sub-tradition, use the exact wording the family uses. Do not infer a sect from a surname or region.','Food preferences, religious practice and family expectations can be included when relevant, but they should be presented as personal or family preferences rather than universal Jain requirements.']},
 {heading:'Keep lineage and family details verified', paragraphs:['Gotra or family lineage information may be requested by some families. If you include it, verify the spelling and source before sharing. A modern biodata can place these fields in an optional section so the main profile remains focused on education, work and personality.','For career details, list qualification, occupation, designation and location clearly. Business owners can describe their sector without publishing confidential accounts or asset details.']},
 {heading:'Privacy and respectful sharing', paragraphs:['A Jain biodata may circulate within a close community network. Keep the first version conservative: no identity numbers, exact house address, passport details or financial documents. A city and family contact are generally enough.','Do not make health, diet or religious-practice assumptions based on community identity. If something matters to the person, let them describe it themselves in the about or expectations section.']},
 {heading:'Final checklist before sharing', paragraphs:['Before publishing a Jain biodata, verify any sect or tradition wording with the family. Jain matrimonial terminology can vary by household, region and tradition, so it is safer to state a person’s actual identity than to infer one from surname or geography.', 'Avoid treating food preference or religious practice as a universal community rule. If vegetarian or other dietary preferences matter to the individual, write them as personal information. The same principle applies to religious practice: describe what the person actually follows.', 'For privacy, keep the first document focused on compatibility and family introduction. Government IDs, financial statements, exact addresses and passport information should not be part of a biodata circulated through a community network. A clear profile photo, short about section and practical career details usually make the document more useful than a long list of traditional fields.', 'If the family uses additional religious or matching documents, keep them separate from the first biodata. This lets the person decide who receives detailed information instead of sending everything in one file. For Jain families, also check that any sect or tradition wording was confirmed by the person rather than inferred. If diet is important, state the actual personal preference. The document should support a respectful conversation, not decide compatibility through assumptions about the wider community.']},
 ],
 fields:[{name:'Jain tradition / sect',explanation:'Use the family’s exact terminology; do not infer it from surname or region.'},{name:'Diet / food preference',explanation:'Useful when it affects daily life; treat it as a personal preference.'},{name:'Gotra / lineage',explanation:'Include only when the family uses it and the information is verified.'},{name:'Religious practice',explanation:'Describe the individual’s actual practice rather than a generic community assumption.'},{name:'Family business / occupation',explanation:'Give a concise sector and role description.'}],
 faqs:[{question:'Should a Jain biodata mention sect?',answer:'It can if the family considers it relevant. Use the exact family terminology and keep the field optional.'},{question:'Should I assume dietary preferences?',answer:'No. If diet matters to the match, state the person’s actual preference directly.'},{question:'Is gotra required?',answer:'Not universally. Include it when the family uses it and has verified the information.'},{question:'How should religious details be written?',answer:'Use factual, respectful language describing the person or family rather than making broad claims about all Jains.'}],
 related:[{href:'/hindu-marriage-biodata-format',label:'Hindu marriage biodata'},{href:'/gujarati-marriage-biodata',label:'Gujarati biodata format'},{href:'/marathi-marriage-biodata',label:'Marathi biodata format'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'muslim', path:'/muslim-marriage-biodata-format', updatedAt:'2026-10-08', lang:'en', name:'Muslim', nativeName:'Muslim', title:'Muslim Marriage Biodata Format | EasyBiodataMaker', description:'Create a Muslim marriage biodata with optional family, sect and personal-practice fields, plus practical privacy guidance.', template:'noor-navy',
 intro:'Muslim matrimonial biodatas vary widely by family, region and tradition. The safest approach is to include the religious and family details that the person actually wants to share, without treating one sect, language or community practice as universal.',
 sections:[
 {heading:'Keep religious identity precise', paragraphs:['If a family wants to mention sect, school or community identity, use the wording they themselves use. Do not infer it from surname, region or appearance. A biodata can simply say Muslim when no further distinction is needed.','Religious practice can be described in personal terms when relevant. For example, a person may choose to mention prayer, modest dress or other practices as part of their own expectations, rather than presenting them as requirements for every Muslim match.']},
 {heading:'Family and career still need clarity', paragraphs:['Parents, siblings, native place, education and occupation are practical core fields. For business families, state the business type and location without publishing confidential financial details. For professionals, qualification, designation and work city are enough for a first introduction.','If the candidate lives abroad, country, city, occupation and broad residency status are useful. Avoid immigration document numbers and do not present legal or visa information as a guarantee of future status.']},
 {heading:'Privacy for matrimonial sharing', paragraphs:['A Muslim marriage biodata may be forwarded through family members or community contacts. Keep the first copy free from identity numbers, passport details, exact home address and sensitive documents. A family contact number is usually sufficient.','Expectations should be respectful and specific. Describe values, location preferences, family involvement and lifestyle priorities without turning the biodata into a list of demands.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing a Muslim marriage biodata, confirm the wording of any sect, school or community field with the person and family. Do not infer religious identity beyond what the person chooses to state. If no distinction is needed, a simple Muslim identity can be enough.', 'Avoid presenting personal religious practice as a universal rule. Prayer, dress, ceremony and lifestyle expectations can be important compatibility topics, but they should be described as the person’s or family’s expectations. Career and education should receive the same careful treatment as religious details.', 'For privacy, do not publish passport numbers, visa numbers, identity documents or exact residential addresses. If the biodata is shared across countries, country and city plus broad residency status are usually enough. Review the expectations section before sending it: a concise description of values and practical preferences is more respectful and useful than a long list of demands.', 'If additional religious, family or matching information is normally exchanged later, keep it in a separate document. The first biodata should be a respectful introduction, not a complete record of the family. For Muslim families, also check that religious identity and personal practice are described separately when useful. If the person has a preferred ceremony style or family involvement, state that as an expectation. Avoid presenting a particular practice as a universal requirement for Muslim matches.']},
 ],
 fields:[{name:'Sect / school of tradition',explanation:'Optional; use the family’s own wording and never infer it.'},{name:'Religious practice',explanation:'Describe the individual’s practice when it is relevant to the match.'},{name:'Family background',explanation:'Keep parents, siblings and native place factual and concise.'},{name:'Residence abroad',explanation:'Country, city and broad residency status are useful for overseas candidates.'},{name:'Marriage expectations',explanation:'Focus on values, location and lifestyle rather than rigid demands.'}],
 faqs:[{question:'Should a Muslim biodata include sect?',answer:'Only if the family considers it relevant. Use the family’s own terminology and keep the field optional.'},{question:'Should religious practice be described?',answer:'It can be, especially if it affects compatibility, but it should describe the individual rather than make universal claims.'},{question:'What should an NRI Muslim biodata include?',answer:'Country, city, occupation and broad residency status are useful; avoid publishing immigration document numbers.'},{question:'How can expectations remain respectful?',answer:'Describe values and practical preferences clearly while avoiding a long list of demands or assumptions about the other family.'}],
 related:[{href:'/hindu-marriage-biodata-format',label:'Hindu marriage biodata'},{href:'/sikh-marriage-biodata',label:'Sikh marriage biodata'},{href:'/christian-marriage-biodata',label:'Christian marriage biodata'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'sikh', path:'/sikh-marriage-biodata', updatedAt:'2026-10-08', lang:'pa', name:'Sikh', nativeName:'ਸਿੱਖ', title:'Sikh Marriage Biodata Format | EasyBiodataMaker', description:'Create a Sikh marriage biodata with practical family, education, career and optional religious-practice fields for private sharing.', template:'royal-peacock',
 intro:'A Sikh marriage biodata should leave room for the family’s own religious and cultural preferences. Some families will care about ceremony and religious practice; others will focus more heavily on education, career and location.',
 sections:[
 {heading:'Describe religious practice accurately', paragraphs:['If Amritdhari status or another aspect of Sikh religious practice matters to the family, include it as a verified personal detail. Do not assume that every Sikh family follows the same level of observance or has the same matrimonial requirements.','If the family wants to mention the intended ceremony, it can be stated in the expectations section. Keep the wording practical and respectful rather than turning the biodata into a religious essay.']},
 {heading:'Family and professional profile', paragraphs:['Parents, siblings, native place, education and occupation are the practical backbone. For professionals, give qualification, role and work location. For business families, describe the sector and location. A clean profile makes it easier for relatives to discuss the match without searching through paragraphs.','For candidates abroad, include country, city and broad residency or citizenship status. Do not publish passport, visa or employer-confidential information.']},
 {heading:'Sharing with dignity and privacy', paragraphs:['Family networks can be large, so the first biodata should be safe to forward. Hide the exact home address if necessary and avoid identity numbers or document scans. One family contact number is enough for the initial version.','Use a recent portrait and up to two additional photos. A modern template can use Sikh-inspired geometry without using religious imagery as decoration by default.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing a Sikh biodata, verify any religious-practice information with the person. Terms such as Amritdhari status should describe the individual accurately, not be used as a generic label. If ceremony preferences matter, write the family’s actual preference without implying that every Sikh family follows it.', 'Avoid replacing useful career information with broad claims about family status. Qualification, occupation, designation, business sector and location help a reader understand the person. Community fields should remain optional because Punjabi and Sikh families can have different priorities.', 'For privacy, prepare a first version that can safely move through family and community contacts. Use city rather than an exact home address, and avoid identity or immigration document numbers. If the candidate lives abroad, include country, city and broad residency status. Check the final image crop and mobile readability before forwarding.', 'If additional family or religious information is exchanged later, keep it separate from the introductory PDF. This allows the person and family to decide what to share at each stage of the conversation. For Sikh families, also check that religious practice is stated as the person’s own information. If ceremony expectations matter, describe them directly. Keep career, education and location equally visible so the biodata presents a complete person rather than only a religious profile.']},
 ],
 fields:[{name:'Religious practice',explanation:'Use accurate personal wording when the family considers it relevant.'},{name:'Ceremony preference',explanation:'Can clarify expectations around the marriage ceremony without assuming a universal practice.'},{name:'Native place',explanation:'Useful for family roots and location context.'},{name:'Education and occupation',explanation:'Keep qualification, role and work city easy to scan.'},{name:'Overseas status',explanation:'Country, city and broad status are useful for diaspora candidates.'}],
 faqs:[{question:'Should Amritdhari status be included?',answer:'If it matters to the person or family, yes. It should be an accurate optional field rather than a universal requirement.'},{question:'Should a Sikh biodata include caste or gotra?',answer:'Only when the family itself uses such information. Do not assume it is required.'},{question:'What should overseas candidates mention?',answer:'Country, city, occupation and broad residency status are useful for the first introduction.'},{question:'How should ceremony expectations be written?',answer:'Keep them clear and respectful, focusing on the family’s actual preference rather than generalizing about Sikh families.'}],
 related:[{href:'/punjabi-marriage-biodata',label:'Punjabi biodata format'},{href:'/muslim-marriage-biodata-format',label:'Muslim marriage biodata'},{href:'/hindu-marriage-biodata-format',label:'Hindu marriage biodata'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
{
 slug:'christian', path:'/christian-marriage-biodata', updatedAt:'2026-10-08', lang:'en', name:'Christian', nativeName:'Christian', title:'Christian Marriage Biodata Format | EasyBiodataMaker', description:'Create a Christian marriage biodata with optional church, denomination, family, education and career fields and practical privacy guidance.', template:'pearl-lavender',
 intro:'Christian marriage biodatas in India can differ by denomination, language, region and family. A useful format avoids assuming one church tradition and lets the person state the information that is genuinely relevant to the match.',
 sections:[
 {heading:'Denomination and church details', paragraphs:['If denomination, church, parish or baptism information matters to the family, include the exact detail the person chooses to share. Catholic, Orthodox, Protestant and other traditions can have different expectations, so the biodata should not present one practice as universal.','A simple “Christian” identity is perfectly valid when no further detail is needed. If church involvement is important, a short line about congregation or service can provide context without making the document overly religious.']},
 {heading:'Family, education and career', paragraphs:['Parents, siblings, native place, education and occupation should remain easy to scan. For candidates working in healthcare, education, technology, government or business, list the role and work location clearly.','For an NRI candidate, country, city and broad residency status are useful. Avoid passport, visa and immigration document numbers.']},
 {heading:'Privacy and expectations', paragraphs:['A Christian biodata may circulate through church, family or community contacts. Keep the first copy conservative and remove identity numbers, exact home addresses and document scans.','Expectations can mention faith practice, location, family involvement and lifestyle preferences if they matter. Use personal language rather than describing what all Christian families should want.']},
 {heading:'Final checklist before sharing', paragraphs:['Before sharing a Christian marriage biodata, confirm the denomination or church terminology with the person. Indian Christian families may identify with different traditions, and the same word can have different significance in different regions. A general Christian identity is perfectly acceptable when no further detail is needed.', 'Avoid turning church affiliation into a universal compatibility rule. If faith practice, baptism or congregation matters to the individual, describe the relevant fact briefly. Keep education, career, family and location equally visible so the biodata remains a balanced introduction.', 'For privacy, remove identity documents, exact addresses and financial records before forwarding. A family contact and city are enough for a first exchange. If the candidate is overseas, use country and city and a broad residency description. Review the expectations section so it describes the person’s own values and preferred family life rather than making claims about all Christian families.', 'If church or family documents are relevant later, exchange them separately rather than attaching them to the first biodata. This keeps the introduction concise and gives the person more control over privacy. For Christian families, also check that denomination and church information are accurate and current. If faith practice matters, describe it in personal terms. Keep education, career, family and location prominent so the document remains useful even when the two families come from different church traditions.']},
 ],
 fields:[{name:'Denomination',explanation:'Optional; use the church tradition the person identifies with.'},{name:'Church / parish',explanation:'Useful only when church affiliation is relevant to the match.'},{name:'Baptism or faith detail',explanation:'Include when the family considers it important and the person is comfortable sharing it.'},{name:'Occupation and location',explanation:'Keep professional details clear and factual.'},{name:'Faith and lifestyle expectations',explanation:'Describe the person’s own preferences rather than making universal claims.'}],
 faqs:[{question:'Should denomination be included?',answer:'If it matters to the family or compatibility, yes. Otherwise a general Christian identity can be enough.'},{question:'Should baptism details be public?',answer:'Only include the level of detail the person is comfortable sharing in an initial biodata.'},{question:'What should an NRI Christian biodata mention?',answer:'Country, city, occupation and broad residency status are useful without publishing immigration document numbers.'},{question:'Can the biodata hide contact details?',answer:'Yes. The builder supports a contact-hidden mode for the final document.'}],
 related:[{href:'/hindu-marriage-biodata-format',label:'Hindu marriage biodata'},{href:'/sikh-marriage-biodata',label:'Sikh marriage biodata'},{href:'/bengali-marriage-biodata',label:'Bengali biodata format'},{href:'/marriage-biodata-formats-by-community',label:'Formats by community'}]
},
];

export const COMMUNITY_BY_PATH = Object.fromEntries(COMMUNITY_PAGES.map((page) => [page.path, page]));
