export type SeoKeywordTarget = { keyword: string; target: string; intent: 'core'|'gender'|'community'|'language'|'writing'|'design'|'maker'|'feature'; existing?: boolean };

export const SEO_KEYWORD_MAP: SeoKeywordTarget[] = [
  // Core & format
  {keyword:'marriage biodata format',target:'/marriage-biodata-format',intent:'core'},
  {keyword:'wedding biodata format',target:'/marriage-biodata-format',intent:'core'},
  {keyword:'biodata for marriage',target:'/marriage-biodata-format',intent:'core'},
  {keyword:'matrimonial biodata format',target:'/marriage-biodata-format',intent:'core'},
  {keyword:'marriage biodata format in word',target:'/marriage-biodata-format-word',intent:'core',existing:true},
  {keyword:'marriage biodata pdf download',target:'/marriage-biodata-format-pdf',intent:'core'},
  {keyword:'biodata format for marriage doc / docx',target:'/marriage-biodata-format-word',intent:'core',existing:true},
  {keyword:'simple biodata format for marriage',target:'/simple-marriage-biodata-format',intent:'core'},
  {keyword:'modern biodata format for marriage',target:'/modern-marriage-biodata-format',intent:'core'},
  {keyword:'marriage biodata template free download',target:'/marriage-biodata-template-free-download',intent:'core'},
  {keyword:'marriage biodata maker online',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'free marriage biodata generator',target:'/marriage-biodata-maker-online',intent:'maker'},
  // Gender / life stage
  {keyword:'biodata format for boy for marriage',target:'/biodata-for-marriage-boy',intent:'gender',existing:true},
  {keyword:'marriage biodata format for girl',target:'/biodata-for-marriage-girl',intent:'gender',existing:true},
  {keyword:'groom biodata format',target:'/biodata-for-marriage-boy',intent:'gender',existing:true},
  {keyword:'bride biodata format',target:'/biodata-for-marriage-girl',intent:'gender',existing:true},
  {keyword:'biodata for second marriage',target:'/blog/second-marriage-biodata-guide',intent:'gender',existing:true},
  {keyword:'divorcee marriage biodata format',target:'/divorcee-marriage-biodata-format',intent:'gender'},
  {keyword:'widow / widower marriage biodata',target:'/widow-widower-marriage-biodata',intent:'gender'},
  {keyword:'late marriage biodata format',target:'/late-marriage-biodata-format',intent:'gender'},
  // Community / religion
  {keyword:'hindu marriage biodata format',target:'/hindu-marriage-biodata-format',intent:'community',existing:true},
  {keyword:'muslim marriage biodata format',target:'/muslim-marriage-biodata-format',intent:'community',existing:true},
  {keyword:'islamic biodata for marriage',target:'/islamic-biodata-for-marriage',intent:'community'},
  {keyword:'christian marriage biodata format',target:'/christian-marriage-biodata',intent:'community',existing:true},
  {keyword:'sikh / anand karaj biodata format',target:'/anand-karaj-biodata-format',intent:'community'},
  {keyword:'jain marriage biodata format',target:'/jain-marriage-biodata',intent:'community',existing:true},
  {keyword:'maratha biodata format',target:'/maratha-biodata-format',intent:'community'},
  {keyword:'brahmin biodata format for marriage',target:'/brahmin-biodata-format-for-marriage',intent:'community'},
  {keyword:'rajput marriage biodata format',target:'/rajput-marriage-biodata-format',intent:'community'},
  {keyword:'kundali / horoscope biodata format',target:'/kundali-marriage-biodata-format',intent:'community'},
  // Language / regional
  {keyword:'marriage biodata in hindi',target:'/hindi-marriage-biodata',intent:'language',existing:true},
  {keyword:'marathi biodata format for marriage',target:'/marathi-marriage-biodata',intent:'language',existing:true},
  {keyword:'gujarati marriage biodata format',target:'/gujarati-marriage-biodata',intent:'language',existing:true},
  {keyword:'tamil matrimony biodata format',target:'/tamil-marriage-biodata',intent:'language',existing:true},
  {keyword:'telugu biodata for marriage',target:'/telugu-marriage-biodata',intent:'language',existing:true},
  {keyword:'bengali marriage biodata',target:'/bengali-marriage-biodata',intent:'language',existing:true},
  {keyword:'kannada marriage biodata format',target:'/kannada-marriage-biodata',intent:'language',existing:true},
  {keyword:'urdu biodata for marriage',target:'/urdu-biodata-for-marriage',intent:'language'},
  // Writing
  {keyword:'about myself for marriage biodata',target:'/about-myself-for-marriage-biodata',intent:'writing'},
  {keyword:'about me sample for matrimony bride / groom',target:'/about-myself-for-marriage-biodata',intent:'writing'},
  {keyword:'partner expectations for marriage biodata',target:'/partner-expectations-for-marriage-biodata',intent:'writing'},
  {keyword:'how to write family details in marriage biodata',target:'/family-details-in-marriage-biodata',intent:'writing'},
  {keyword:'strengths and hobbies to write in marriage biodata',target:'/about-myself-for-marriage-biodata',intent:'writing'},
  {keyword:'marriage biodata profile summary examples',target:'/marriage-biodata-profile-summary-examples',intent:'writing'},
  // Design
  {keyword:'marriage biodata template canva',target:'/marriage-biodata-template-free-download',intent:'design'},
  {keyword:'marriage biodata photoshop psd free download',target:'/marriage-biodata-template-free-download',intent:'design'},
  {keyword:'royal wedding biodata format',target:'/royal-wedding-biodata-format',intent:'design'},
  {keyword:'traditional marriage biodata template',target:'/traditional-marriage-biodata-template',intent:'design'},
  {keyword:'marriage biodata design with photo frame',target:'/biodata-maker-with-photo',intent:'design'},
  {keyword:'editable marriage biodata google docs',target:'/marriage-biodata-format-word',intent:'design',existing:true},
  {keyword:'single page marriage biodata format',target:'/single-page-marriage-biodata-format',intent:'design'},
  // Easy/simple maker
  {keyword:'easy bio data maker',target:'/',intent:'maker',existing:true},
  {keyword:'simple bio data maker',target:'/simple-marriage-biodata-format',intent:'maker'},
  {keyword:'easy marriage biodata maker',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'simple biodata maker for marriage',target:'/simple-marriage-biodata-format',intent:'maker'},
  {keyword:'simple biodata creator online',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'quick bio data maker',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'fast biodata maker online',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'easy bio data builder',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'simplest biodata format maker',target:'/simple-marriage-biodata-format',intent:'maker'},
  {keyword:'biodata maker in 2 minutes / 5 minute biodata maker',target:'/marriage-biodata-maker-online',intent:'maker'},
  // Free / download
  {keyword:'free bio data maker',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'free online biodata maker without login',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'free marriage biodata maker without registration',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'biodata maker online free pdf download',target:'/marriage-biodata-format-pdf',intent:'maker'},
  {keyword:'instant marriage biodata maker',target:'/marriage-biodata-maker-online',intent:'maker'},
  {keyword:'auto biodata maker free',target:'/marriage-biodata-maker-online',intent:'maker'},
  // Mobile / WhatsApp
  {keyword:'bio data maker app download',target:'/biodata-maker-for-mobile',intent:'maker'},
  {keyword:'biodata maker for mobile',target:'/biodata-maker-for-mobile',intent:'maker'},
  {keyword:'marriage biodata maker apk',target:'/biodata-maker-for-mobile',intent:'maker'},
  {keyword:'biodata maker for whatsapp sharing',target:'/biodata-maker-for-whatsapp',intent:'maker'},
  {keyword:'online bio data maker on phone',target:'/biodata-maker-for-mobile',intent:'maker'},
  {keyword:'biodata maker app without ads',target:'/biodata-maker-for-mobile',intent:'maker'},
  // Language tools
  {keyword:'simple biodata maker in hindi',target:'/hindi-marriage-biodata',intent:'language',existing:true},
  {keyword:'marathi biodata maker online',target:'/marathi-marriage-biodata',intent:'language',existing:true},
  {keyword:'gujarati marriage biodata maker',target:'/gujarati-marriage-biodata',intent:'language',existing:true},
  {keyword:'tamil biodata maker online free',target:'/tamil-marriage-biodata',intent:'language',existing:true},
  {keyword:'telugu wedding biodata creator',target:'/telugu-marriage-biodata',intent:'language',existing:true},
  {keyword:'bilingual biodata maker',target:'/bilingual-biodata-maker',intent:'language'},
  // Features
  {keyword:'biodata maker with photo upload',target:'/biodata-maker-with-photo',intent:'feature'},
  {keyword:'biodata maker with god photo / ganesh photo',target:'/biodata-maker-with-ganesh-photo',intent:'feature'},
  {keyword:'biodata maker word document export',target:'/marriage-biodata-format-word',intent:'feature'},
  {keyword:'biodata maker pdf 1 page',target:'/marriage-biodata-format-pdf',intent:'feature'},
  {keyword:'biodata maker with kundali / horoscope section',target:'/kundali-marriage-biodata-format',intent:'feature'},
  {keyword:'ready-made biodata maker with sample text',target:'/marriage-biodata-maker-online',intent:'feature'},
];
