import type { SearchIntentPageConfig } from '@/components/seo/SearchIntentLandingPage';

export const SEARCH_INTENT_PAGES: SearchIntentPageConfig[] = [
  {
    path: '/marriage-biodata-format', title: 'Marriage Biodata Format | Free A4 Guide', updatedAt: '2026-10-08',
    description: 'Learn what a marriage biodata format should contain and create a polished A4 biodata online with photos, family, career and expectations.',
    eyebrow: 'Core format guide',
    intro: 'A marriage biodata is a concise introduction used by families or individuals when considering a matrimonial match. The strongest format is easy to scan, honest about important details, and flexible enough to remove fields that do not apply.',
    quickAnswer: 'A useful marriage biodata format normally includes personal details, family background, education and career, a short introduction, partner expectations, a safe contact method and a clear profile photo. Optional fields such as gotra, horoscope details, caste or community should be included only when they are relevant to the family.',
    sections: [
      { heading: 'What to include on the first page', paragraphs: [
        'Start with the person rather than a long family history. Full name, date of birth, height, education, occupation, current city and a profile photograph give a reader enough context to decide whether to continue. A clean two-column layout can make a detailed profile fit comfortably on one A4 page without shrinking the type too far.',
        'Family details can follow in a compact section: parents, siblings, family background and native place. Add only facts that the family is comfortable circulating. A full home address, identity numbers and other sensitive information are usually unnecessary in an introductory biodata.' ] },
      { heading: 'Traditional and modern fields can coexist', paragraphs: [
        'Indian marriage biodatas vary widely. Some families expect caste, sub-caste, gotra, manglik status, rashi or nakshatra; others care more about education, career, location and personality. A good format treats these as optional fields rather than assuming every family follows one matching system.',
        'The same principle applies to income, family business, NRI status and relocation plans. State useful information clearly, but avoid turning the document into a financial or identity record. EasyBiodataMaker lets you keep the predefined structure and add or remove individual fields.' ] },
      { heading: 'Make the profile easy to read and share', paragraphs: [
        'Use short values instead of paragraphs wherever possible. For example, “Software Engineer · Ahmedabad” is easier to scan than a long sentence about employment. Keep the About Me and expectations sections conversational and specific rather than filling them with generic adjectives.',
        'Before sharing, open the PDF on a phone. Names, dates, phone numbers and regional scripts should remain readable. Keep a private copy with sensitive information and a shareable version with only what is necessary for the first introduction.' ] },
    ],
    checklist: ['Full name, age/date of birth and height', 'Education, occupation and current city', 'Parents and sibling information', 'Optional community or horoscope fields', 'A short About Me and partner expectations', 'One clear profile photo and safe contact details'],
    related: [
      { href: '/marriage-biodata-format', label: 'Biodata for marriage' }, { href: '/simple-marriage-biodata-format', label: 'Simple biodata format' }, { href: '/modern-marriage-biodata-format', label: 'Modern biodata format' },
      { href: '/marriage-biodata-format-word', label: 'Marriage biodata format in Word' }, { href: '/marriage-biodata-format-pdf', label: 'Marriage biodata PDF' }, { href: '/marriage-biodata-formats-by-community', label: 'Community formats' },
    ],
    faqs: [
      { question: 'What is the standard marriage biodata format?', answer: 'A practical format contains personal details, family background, education and career, About Me, expectations, contact information and a profile photo. Traditional fields can be added when relevant.' },
      { question: 'Should a marriage biodata be one page?', answer: 'One page is ideal for a concise first introduction, but a second page can be useful when the family wants more detail or additional photos. The content should stay readable rather than being squeezed to fit.' },
      { question: 'Can I make a marriage biodata without login?', answer: 'Yes. EasyBiodataMaker is designed for browser-based creation without requiring an account.' },
      { question: 'Can I remove fields I do not want?', answer: 'Yes. The builder lets you hide or remove fields and add optional custom fields when the predefined structure does not cover your family’s needs.' },
    ],
  },
  {
    path: '/marriage-biodata-format-pdf', title: 'Marriage Biodata PDF | A4 Download & Print', updatedAt: '2026-10-08',
    description: 'Create a marriage biodata PDF in A4 format with selectable text, a profile photo and optional separate photo pages for sharing or printing.',
    eyebrow: 'PDF format',
    intro: 'A marriage biodata PDF is useful when the finished profile needs to be printed, emailed or forwarded without changing its layout. A4 sizing and readable text matter more than simply exporting a screenshot.',
    quickAnswer: 'For a good marriage biodata PDF, use A4 portrait sizing, keep text selectable, reserve space for the footer and avoid shrinking the content so much that names and dates become difficult to read. Additional photos can be placed on dedicated pages.',
    sections: [
      { heading: 'Why A4 matters', paragraphs: ['A4 is familiar to Indian families, printers and office software. Designing around the actual page dimensions makes the PDF more predictable when someone prints it at home or at a local shop.', 'A one-page biodata is useful when the content fits comfortably. If it does not, a deliberate second page is better than squeezing everything into tiny type.'] },
      { heading: 'PDF versus PNG', paragraphs: ['PDF is the better choice for printing and formal sharing because the text can remain selectable and the page dimensions are explicit. PNG is useful for WhatsApp previews and situations where an image is easier to open.', 'For profiles with several photos, a clean PDF can use a main biodata page followed by dedicated photo pages. This keeps the primary information readable.'] },
      { heading: 'Check before sending', paragraphs: ['Open the exported PDF on a phone and desktop. Verify regional scripts, names, dates, phone numbers and the profile photograph. If the document has more than one page, confirm that the page break is intentional rather than caused by overflow.', 'Keep a source copy in the browser and regenerate the PDF if the profile changes. Avoid editing the exported PDF manually when the builder can recreate it consistently.'] },
    ],
    checklist: ['A4 portrait page', 'Readable text at normal zoom', 'Selectable text', 'Profile photo positioned cleanly', 'Additional photos on intentional pages', 'Footer without overlap'],
    related: [{ href: '/marriage-biodata-format-word', label: 'Word / DOCX format' }, { href: '/marriage-biodata-format-pdf', label: 'One-page PDF maker' }, { href: '/single-page-marriage-biodata-format', label: 'Single-page format' }, { href: '/create', label: 'Create and save PDF' }],
    faqs: [
      { question: 'Can I download a marriage biodata as PDF?', answer: 'Yes. The builder uses the browser print flow so the finished document can be saved as an A4 PDF.' },
      { question: 'Will the PDF text be selectable?', answer: 'The print-oriented export is designed to preserve the document text rather than turning the entire page into one bitmap.' },
      { question: 'Can extra photos be separate pages?', answer: 'Yes. The photo-page options allow additional images to appear as dedicated pages or together on a photo gallery page.' },
      { question: 'Is one page always better?', answer: 'Not if it makes the text too small. A clean second page is preferable when additional content genuinely needs space.' },
    ],
  },
  {
    path: '/simple-marriage-biodata-format', title: 'Simple Marriage Biodata Format | Clean & Easy', updatedAt: '2026-10-08',
    description: 'Create a simple marriage biodata format with clear fields, minimal decoration, a profile photo and an A4 PDF that stays easy to read.',
    eyebrow: 'Simple format',
    intro: 'A simple marriage biodata format is not a bare document. It is a format where the information hierarchy is stronger than the decoration. This is useful for families that want a straightforward profile that can be printed and forwarded easily.',
    quickAnswer: 'Use five or six clear sections, short field values, one strong profile photo and a short About Me. Remove optional fields that are not relevant and keep the final document readable at normal phone zoom.',
    sections: [
      { heading: 'Keep the information hierarchy strong', paragraphs: ['Personal, Family, Education & Career, About Me and Contact are enough for many profiles. Optional community or horoscope fields can be placed inside the relevant section rather than creating many tiny blocks.', 'Simple design also makes proofreading easier. If a date, city or name is wrong, it is easier to spot before the biodata is shared widely.'] },
      { heading: 'Simple does not mean generic', paragraphs: ['Use the About Me section to add two or three real details: a hobby, a work interest, a family value or the kind of life you enjoy. A small amount of specific writing can make a simple format feel personal.', 'For partner expectations, write what matters rather than a long list of requirements. “Open to relocation and looking for a respectful, family-oriented partner” is more useful than ten vague adjectives.'] },
      { heading: 'Best for fast sharing', paragraphs: ['Simple formats work particularly well when relatives forward them on WhatsApp. Keep the first page focused and move additional photos to separate pages. A PDF remains useful for printing, while a PNG is convenient for quick messaging.', 'If the family wants a Word document for later editing, use the DOCX export rather than copying text out of a screenshot.'] },
    ],
    checklist: ['Five core sections', 'One clear profile photo', 'Short values and expectations', 'Only relevant optional fields', 'Readable A4 output', 'Safe contact details'],
    related: [{ href: '/modern-marriage-biodata-format', label: 'Modern format' }, { href: '/single-page-marriage-biodata-format', label: 'Single-page format' }, { href: '/marriage-biodata-format-pdf', label: 'PDF guide' }, { href: '/create', label: 'Create a simple biodata' }],
    faqs: [
      { question: 'What is a simple marriage biodata format?', answer: 'It is a concise profile with clear sections and minimal decoration. It should still include the information needed for a meaningful first introduction.' },
      { question: 'Can I remove fields?', answer: 'Yes. You can hide optional fields and reorder the predefined fields to match your family’s priorities.' },
      { question: 'Is a simple format suitable for WhatsApp?', answer: 'Yes. A clean single-page image or PDF is easy to view and forward on a phone.' },
      { question: 'Can I add a custom field?', answer: 'Yes. Custom fields can be added at the bottom of the relevant category when the predefined fields do not cover a specific need.' },
    ],
  },
  {
    path: '/modern-marriage-biodata-format', title: 'Modern Marriage Biodata Format | Clean Design', updatedAt: '2026-10-08',
    description: 'Create a modern marriage biodata format with clean typography, optional community fields, photos and flexible section order.',
    eyebrow: 'Modern format',
    intro: 'A modern biodata can respect traditional matrimonial expectations while presenting the information in a cleaner way. The goal is not to remove cultural fields; it is to make the document easier to understand and less crowded.',
    quickAnswer: 'A modern marriage biodata usually combines structured facts, restrained design, a natural photo, a concise personal summary and optional traditional fields such as gotra or horoscope details. The user should be able to reorder or remove fields without rebuilding the profile.',
    sections: [
      { heading: 'Modern design is mostly about hierarchy', paragraphs: ['Use whitespace, consistent labels and short values. Avoid putting every detail in a decorative card. The reader should be able to find education, career and family information quickly.', 'Modern formats can still use Indian visual language: a subtle motif, a religious symbol selected by the user or a warm colour palette can create cultural context without overwhelming the page.'] },
      { heading: 'Let the person speak', paragraphs: ['The About Me section is one of the easiest places to make a biodata feel current. Mention interests, routines, values and what you enjoy about your work or family life. Avoid phrases such as “simple, sober, cultured” unless you explain what they mean for you.', 'Expectations should also be specific. Location flexibility, career plans, family involvement and lifestyle preferences are more informative than a long list of ideal traits.'] },
      { heading: 'Customisation without losing structure', paragraphs: ['The builder starts with predefined fields so users do not have to design a form from scratch. You can remove a field, move it up or down, or add a custom field when something unique matters to your family.', 'This approach works for modern profiles because the document stays consistent even after personalisation.'] },
    ],
    checklist: ['Clean information hierarchy', 'User-selected religious/community symbol if desired', 'Optional traditional fields', 'Short personal summary', 'Reorderable fields', 'A4 PDF and editable Word output'],
    related: [{ href: '/traditional-marriage-biodata-template', label: 'Traditional template' }, { href: '/royal-wedding-biodata-format', label: 'Royal wedding format' }, { href: '/templates', label: 'Explore designs' }, { href: '/create', label: 'Create a modern biodata' }],
    faqs: [
      { question: 'Can a modern biodata include gotra and horoscope fields?', answer: 'Yes. Modern presentation does not require removing traditional information. The fields can remain optional and user-controlled.' },
      { question: 'Can I change the order of sections?', answer: 'Yes. The builder supports section and field reordering so the profile can reflect individual preferences.' },
      { question: 'Can I add religious icons?', answer: 'Yes. Supported community presets can suggest appropriate header symbols, while the user can choose a different available symbol.' },
      { question: 'Is a modern biodata still suitable for parents?', answer: 'Yes. A clear hierarchy and familiar section names can make a modern design easier to scan than a dense traditional document.' },
    ],
  },
  {
    path: '/marriage-biodata-template-free-download', title: 'Marriage Biodata Template | Free Online Format', updatedAt: '2026-10-08',
    description: 'Explore free marriage biodata templates that can be customised online, exported to PDF or Word and adapted for Indian families.',
    eyebrow: 'Free templates',
    intro: 'A free marriage biodata template is useful when you want a starting structure instead of designing the document from scratch. The important question is whether the template can be personalised without breaking its layout.',
    quickAnswer: 'Choose a template with a clear field hierarchy, replaceable photo, editable text and A4 output. Avoid templates that force every family into the same set of fields or require you to rebuild the design manually in a graphics editor.',
    sections: [
      { heading: 'What a useful free template should provide', paragraphs: ['The template should cover common personal, family, education, career and contact information while allowing optional fields to be hidden. It should also keep enough room for longer names and regional-language text.', 'A good template is more than a decorative image. It should produce a document that remains readable after real information replaces the sample text.'] },
      { heading: 'Free download versus online maker', paragraphs: ['A static download gives you a starting file but usually leaves formatting work to you. An online maker can keep the field structure and design connected, making it easier to change a photo, remove a field or reorder information.', 'If you need a Word document, use an actual DOCX export. If you need a print-ready copy, use the A4 PDF flow. For quick WhatsApp sharing, an image export can be more convenient.'] },
      { heading: 'Choosing between online templates and design software', paragraphs: ['Search results may also point to Canva designs, Photoshop PSD files or editable Google Docs templates. EasyBiodataMaker does not provide those source-file formats. Instead, it provides a browser-based biodata workflow where the fields, photo handling and supported exports stay connected.', 'A dedicated marriage biodata maker keeps the matrimonial fields, photo handling and A4 export together. Choose the workflow that gives your family the least formatting work while keeping the final document readable and editable.'] },
      { heading: 'Choosing a template for your family', paragraphs: ['Traditional, modern, royal and minimalist designs can all work. Pick based on readability and family preference rather than claims that one style is universally best.', 'Community presets can provide a starting point for Gujarati, Marathi, Hindi, Jain, Muslim, Sikh or Christian profiles, while keeping optional fields under the user’s control.'] },
    ],
    checklist: ['A4-ready layout', 'Editable information', 'Photo support', 'Optional field controls', 'Regional-language support', 'PDF and Word export'],
    related: [{ href: '/templates', label: 'Template gallery' }, { href: '/marriage-biodata-format-word', label: 'Editable Word format' }, { href: '/marriage-biodata-format-pdf', label: 'PDF format' }, { href: '/create', label: 'Use a free template' }],
    faqs: [
      { question: 'Can I download a free marriage biodata template?', answer: 'Yes. You can create a profile from the available designs and export the finished document rather than editing a static screenshot.' },
      { question: 'Can I change fields in a template?', answer: 'Yes. The builder allows fields to be removed, reordered and extended with custom fields.' },
      { question: 'Can I use the template in a regional language?', answer: 'Yes. The builder supports multiple Indian scripts with script-aware typography.' },
      { question: 'Can I edit the finished biodata in Word?', answer: 'Yes. The Word export creates an editable DOCX document.' },
    ],
  },
  {
    path: '/marriage-biodata-maker-online', title: 'Marriage Biodata Maker Online | Free & Private', updatedAt: '2026-10-08',
    description: 'Use an online marriage biodata maker to create a private Indian matrimonial profile with photos, templates, PDF and Word export.',
    eyebrow: 'Online maker',
    intro: 'An online marriage biodata maker is useful when you want to create the document from a phone or computer without installing design software. The best workflow combines a guided form with a live preview so you can see the finished page before exporting it.',
    quickAnswer: 'Choose a template, fill the predefined fields, add or remove optional information, upload photos, preview the result and export it. A privacy-first browser workflow avoids the need to create an account just to prepare a marriage biodata.',
    sections: [
      { heading: 'Why an online builder is easier than starting in Word', paragraphs: ['Word is excellent for editing text, but a biodata often needs deliberate visual hierarchy, photo cropping and page layout. An online builder can keep those elements connected while you fill the form.', 'You can still export to DOCX when you want an editable Word document later. This gives you the convenience of an online maker without locking the final document into one format.'] },
      { heading: 'Build once, try multiple designs', paragraphs: ['The content and template are separate, so you can test traditional, modern or royal styles without retyping the profile. This is useful when different family members have different preferences about colours or decorative elements.', 'Community presets can suggest fields and symbols, while every field remains optional and reorderable.'] },
      { heading: 'Designed for sharing', paragraphs: ['A4 PDF is useful for printing and formal forwarding. PNG is useful for quick WhatsApp sharing. Additional photos can be placed on separate pages instead of crowding the main biodata.', 'Always check the final export on the device you will use for sharing. A good online maker should make that final check easy with a live preview.'] },
    ],
    checklist: ['Browser-based creation', 'Live template preview', 'No-login workflow', 'Field reorder and custom fields', 'A4 PDF and DOCX export', 'WhatsApp-friendly image sharing'],
    related: [{ href: '/marriage-biodata-maker-online', label: 'Free generator' }, { href: '/biodata-maker-for-mobile', label: 'Mobile guide' }, { href: '/biodata-maker-for-whatsapp', label: 'WhatsApp sharing' }, { href: '/create', label: 'Create online' }],
    faqs: [
      { question: 'Do I need to install an app?', answer: 'No. The maker runs in a modern web browser.' },
      { question: 'Can I use it without registration?', answer: 'Yes. The creation flow is designed without a required account.' },
      { question: 'Can I edit the same profile in another template?', answer: 'Yes. The biodata information and template choice are kept separate.' },
      { question: 'Can I create a Word document?', answer: 'Yes. The builder includes a real DOCX export for further editing.' },
    ],
  },
  {
    path: '/divorcee-marriage-biodata-format', title: 'Divorcee Marriage Biodata Format | Practical Guide', updatedAt: '2026-10-08',
    description: 'A respectful divorcee marriage biodata format with practical guidance for previous marriage details, family, career and privacy.',
    eyebrow: 'Second-chapter profiles',
    intro: 'A divorcee marriage biodata should be factual, respectful and focused on the person’s present life. It does not need to turn a previous marriage into the headline of the document, but it should not hide a fact that is important to a serious matrimonial conversation.',
    quickAnswer: 'Keep the current profile prominent: personal details, education, career, family, interests and expectations. Mention a previous marriage briefly and accurately in a dedicated note when appropriate, and discuss legal or sensitive details privately rather than putting them into a widely forwarded document.',
    sections: [
      { heading: 'Use direct, neutral language', paragraphs: ['Avoid euphemisms that create confusion and avoid long explanations. A short statement such as “Previously married; legally divorced” may be enough for an introductory profile if that wording is accurate for the person.', 'If children, custody, relocation or other matters are relevant to a future match, describe them honestly in a way that respects privacy. Detailed legal documents do not belong in a public biodata.'] },
      { heading: 'Let the current person lead the profile', paragraphs: ['Education, career, family relationships, hobbies and expectations should have as much space as they would in any other marriage biodata. A second-chapter profile is still a complete introduction to a person.', 'Do not make claims about why a previous marriage ended unless the person is comfortable discussing them privately. The biodata should not become a public narrative about another person.'] },
      { heading: 'Share with care', paragraphs: ['Because these profiles can be forwarded widely, use a conservative contact and address strategy. Share additional personal or legal information only with a trusted family after both sides decide to continue.', 'The same PDF and Word export options work for a divorcee profile. The difference is primarily in wording and privacy, not in the quality of the design.'] },
    ],
    checklist: ['Present-day personal and career details', 'Brief accurate previous-marriage note when appropriate', 'Relevant children/family information', 'Clear expectations', 'Privacy-safe contact details', 'Respectful language throughout'],
    related: [{ href: '/blog/second-marriage-biodata-guide', label: 'Second marriage guide' }, { href: '/late-marriage-biodata-format', label: 'Late marriage format' }, { href: '/marriage-biodata-format', label: 'General marriage profile' }, { href: '/create', label: 'Create a profile' }],
    faqs: [
      { question: 'Should a divorcee mention the previous marriage?', answer: 'For a serious matrimonial introduction, relevant previous-marriage information should be truthful. Keep the initial note concise and discuss sensitive details privately.' },
      { question: 'Should legal documents be attached?', answer: 'Not to a general biodata. Share legal documents privately and only when they are needed.' },
      { question: 'Should children be mentioned?', answer: 'If children are part of the person’s current family situation and relevant to a potential match, they should be represented honestly.' },
      { question: 'Can a divorcee use a normal biodata template?', answer: 'Yes. The same professional template can be used; the main difference is the wording and the amount of sensitive detail shared.' },
    ],
  },
  {
    path: '/widow-widower-marriage-biodata', title: 'Widow & Widower Marriage Biodata | Practical Guide', updatedAt: '2026-10-08',
    description: 'Create a respectful widow or widower marriage biodata with current family, career, children, expectations and privacy guidance.',
    eyebrow: 'Respectful profile guide',
    intro: 'A widow or widower marriage biodata should present the person as a complete individual today. A previous loss may be relevant to a matrimonial conversation, but the profile should not reduce someone’s identity to that event.',
    quickAnswer: 'Lead with the person’s current life: age, education, work, family, children where relevant, interests and expectations. Mention previous marital status accurately and briefly, then leave detailed personal history for a private conversation.',
    sections: [
      { heading: 'Focus on the current life', paragraphs: ['The same core sections used in other marriage biodatas still work: personal details, family, education and career, About Me and expectations. The difference is that family structure may need a little more clarity when children or dependent relatives are involved.', 'Use respectful language and avoid unnecessary details about the deceased spouse. The biodata is an introduction to the person who is considering a new chapter.'] },
      { heading: 'Children and family context', paragraphs: ['If children are part of the household, state that clearly when it matters to a potential match. Age, living arrangement or broad family context can be discussed without publishing school names, addresses or other identifying information.', 'Expectations can also clarify whether the person is open to relocation, remarriage with someone who has children, or other family arrangements.'] },
      { heading: 'Privacy and emotional care', paragraphs: ['These profiles can be especially sensitive when forwarded. Keep the first version concise and avoid personal photographs or information about relatives that they did not agree to share.', 'A calm, readable design is often more appropriate than a highly decorative layout. The goal is clarity and dignity.'] },
    ],
    checklist: ['Current personal profile', 'Accurate marital-status wording', 'Children/family context when relevant', 'Education and career', 'Realistic expectations', 'Privacy-safe sharing'],
    related: [{ href: '/divorcee-marriage-biodata-format', label: 'Divorcee format' }, { href: '/late-marriage-biodata-format', label: 'Late marriage format' }, { href: '/marriage-biodata-format', label: 'General profile guide' }, { href: '/create', label: 'Create a biodata' }],
    faqs: [
      { question: 'Should a widow or widower mention children?', answer: 'If children are part of the current family situation and relevant to a future match, yes. Keep the information factual and privacy-conscious.' },
      { question: 'Should the previous spouse be described in detail?', answer: 'Usually no. A concise, accurate statement about marital status is enough for an introductory biodata.' },
      { question: 'Can the same templates be used?', answer: 'Yes. The profile can use any of the available designs.' },
      { question: 'What should expectations include?', answer: 'Mention the family, location, lifestyle or support arrangements that genuinely matter to the person. Keep the section open to conversation.' },
    ],
  },
  {
    path: '/late-marriage-biodata-format', title: 'Late Marriage Biodata Format | Mature & Modern', updatedAt: '2026-10-08',
    description: 'A late marriage biodata format for mature profiles, with career, family, lifestyle, expectations and optional age-related context.',
    eyebrow: 'Mature profiles',
    intro: 'A late marriage biodata does not need to apologise for age. It should make the person’s current life easy to understand: career, family responsibilities, interests, location, lifestyle and what they want from a partnership.',
    quickAnswer: 'For a mature marriage profile, prioritise current life and compatibility. Education, career, family responsibilities, health or lifestyle details that the person chooses to share, interests and realistic expectations are more useful than defensive explanations about age.',
    sections: [
      { heading: 'Write for compatibility, not justification', paragraphs: ['A mature profile can be more direct than a younger profile because the person often knows what matters to them. Say whether you want to continue a career, relocate, live with parents, travel or maintain a particular lifestyle.', 'Avoid phrases that frame age as a problem. The biodata should communicate confidence, not ask the reader for permission to consider the person.'] },
      { heading: 'Family responsibilities can be important', paragraphs: ['If parents, adult children or other family responsibilities affect future plans, explain the broad situation. This can prevent misunderstandings later without disclosing private details about relatives.', 'The same applies to location. A mature professional may have a long-established career or home city. State what is flexible and what is not.'] },
      { heading: 'A strong About Me matters', paragraphs: ['Use the personal section to show what life is like now: hobbies, work interests, travel, community involvement or the kind of weekends you enjoy. This creates a fuller picture than a list of qualifications.', 'Partner expectations should focus on mutual respect and practical compatibility rather than a long list of age-specific conditions.'] },
    ],
    checklist: ['Current age and personal details', 'Established career and location', 'Family responsibilities', 'Lifestyle and interests', 'Practical expectations', 'Respectful, confident language'],
    related: [{ href: '/marriage-biodata-format', label: 'Biodata for marriage' }, { href: '/divorcee-marriage-biodata-format', label: 'Divorcee format' }, { href: '/widow-widower-marriage-biodata', label: 'Widow/widower format' }, { href: '/create', label: 'Create your profile' }],
    faqs: [
      { question: 'Should a late marriage biodata explain why someone married later?', answer: 'Only if the person wants to discuss it. The profile can focus on current life and compatibility instead of giving a defensive explanation.' },
      { question: 'Should career details be more prominent?', answer: 'If career and location are important to the person’s current life, yes. State the role, industry and city clearly.' },
      { question: 'Can I mention family responsibilities?', answer: 'Yes, when they affect future plans. Keep details factual and avoid exposing relatives’ private information.' },
      { question: 'What makes a mature biodata attractive?', answer: 'Clarity, confidence, honest expectations and a realistic picture of everyday life.' },
    ],
  },
  {
    path: '/kundali-marriage-biodata-format', title: 'Kundali Marriage Biodata | Gotra, Rashi & Nakshatra', updatedAt: '2026-10-08',
    description: 'Create a marriage biodata with optional kundali fields including gotra, rashi, nakshatra, manglik status and birth details.',
    eyebrow: 'Horoscope-aware format',
    intro: 'Some families want the marriage biodata to carry a compact summary of the information used alongside a kundali or horoscope. Others exchange a separate horoscope document. This guide keeps those choices optional.',
    quickAnswer: 'A kundali-friendly marriage biodata can include date, time and place of birth plus optional gotra, rashi, nakshatra, manglik status and other family-approved fields. It should not replace the family’s actual horoscope document when one is required.',
    sections: [
      { heading: 'Birth details first', paragraphs: ['Date, time and place of birth are the most useful source fields because they can be used to prepare or cross-check a separate horoscope. Enter them exactly as the family record provides them.', 'If the time of birth is uncertain, say so rather than inventing a precise time. Accuracy is more valuable than filling every box.'] },
      { heading: 'Optional matching fields', paragraphs: ['Gotra, rashi, nakshatra and manglik status can be added when the family uses them. These terms and matching practices vary, so the biodata should record the family-provided information rather than trying to infer it automatically.', 'If the family uses a separate kundali, link or mention it in the sharing conversation instead of putting a full chart on the main biodata page.'] },
      { heading: 'Keep the human profile visible', paragraphs: ['Horoscope information should not crowd out education, career, family and personality. A matrimonial profile still needs to answer the basic question: who is this person and what kind of life are they building?', 'Use the optional-field controls to keep the document focused. Add custom fields only when a specific family practice requires them.'] },
    ],
    checklist: ['Accurate birth date', 'Birth time and place', 'Gotra when relevant', 'Rashi and nakshatra when verified', 'Manglik status if family uses it', 'Separate kundali when needed'],
    related: [{ href: '/hindu-marriage-biodata-format', label: 'Hindu marriage biodata' }, { href: '/marriage-biodata-format', label: 'Core format guide' }, { href: '/marriage-biodata-formats-by-community', label: 'Community formats' }, { href: '/create', label: 'Create a kundali-friendly biodata' }],
    faqs: [
      { question: 'What kundali fields can be included?', answer: 'Common optional fields include birth date, birth time, birth place, gotra, rashi, nakshatra and manglik status. Families should use the information they have verified.' },
      { question: 'Should the full kundali be inside the biodata?', answer: 'Usually it is cleaner to keep the full horoscope as a separate document and use the biodata for a compact summary.' },
      { question: 'Is gotra required for every Hindu biodata?', answer: 'No. It depends on family and community practice, so it should remain optional.' },
      { question: 'Can I add a custom horoscope field?', answer: 'Yes. Custom fields can be added when a family uses a term not included in the predefined structure.' },
    ],
  },
  {
    path: '/urdu-biodata-for-marriage', title: 'Urdu Biodata for Marriage | Matrimonial Format', updatedAt: '2026-10-08',
    description: 'Create an Urdu-friendly biodata for marriage with a clean structure, optional Islamic fields and readable regional-script support.',
    eyebrow: 'Language format',
    intro: 'Families who prefer Urdu can use the same practical marriage-biodata structure while choosing labels and writing that fit their language preference. The important part is keeping the profile accurate and readable rather than translating every field mechanically.',
    quickAnswer: 'An Urdu biodata for marriage can include personal details, family, education, occupation, religious information where relevant, About Me, expectations and contact details. Keep Arabic/Urdu religious terminology accurate and let the user decide which fields belong in the final profile.',
    sections: [
      { heading: 'Language should serve the family', paragraphs: ['A bilingual or Urdu-first profile can help parents and relatives read the important details comfortably. Use consistent script and spelling for names, cities and occupations.', 'If the profile is shared with people who prefer English, a bilingual version can be useful. Keep the two versions aligned rather than translating one section and leaving another in a different language.'] },
      { heading: 'Islamic and family details', paragraphs: ['Depending on the family, fields such as sect or school of thought, prayer practice, halal lifestyle, family background or other religious preferences may be relevant. These should remain optional and should reflect the person’s own wording.', 'Avoid inventing religious classifications. If a field is important but unclear, confirm it with the family rather than selecting a label simply because it appears in a template.'] },
      { heading: 'Readable export', paragraphs: ['Script-aware fonts matter when a document is printed or exported. Check the final PDF on both phone and desktop and make sure Urdu text does not break or become too small.', 'For WhatsApp, an image can be convenient; for formal sharing, an A4 PDF is easier to print and archive.'] },
    ],
    checklist: ['Correct Urdu spelling', 'Consistent bilingual labels if used', 'Optional Islamic/community fields', 'Clear education and occupation', 'Privacy-safe contact details', 'Check exported script on a phone'],
    related: [{ href: '/muslim-marriage-biodata-format', label: 'Muslim marriage biodata' }, { href: '/bilingual-biodata-maker', label: 'Bilingual biodata maker' }, { href: '/hindi-marriage-biodata', label: 'Hindi biodata format' }, { href: '/create', label: 'Create your biodata' }],
    faqs: [
      { question: 'Can I make a marriage biodata in Urdu?', answer: 'Yes. The project supports regional-script workflows and the content structure can be used for Urdu-focused profiles.' },
      { question: 'Should Islamic fields be mandatory?', answer: 'No. They should be included only when they are relevant to the person and family.' },
      { question: 'Can I make a bilingual biodata?', answer: 'Yes. A bilingual profile can present English alongside a regional language when both audiences need to read it.' },
      { question: 'How should I check the final PDF?', answer: 'Open it on a phone and desktop and verify names, Urdu shaping, dates and contact information before sharing.' },
    ],
  },
  {
    path: '/bilingual-biodata-maker', title: 'Bilingual Biodata Maker | English + Indian Language', updatedAt: '2026-10-08',
    description: 'Create a bilingual marriage biodata in English and an Indian language with script-aware labels, flexible fields and A4 export.',
    eyebrow: 'Language-friendly builder',
    intro: 'A bilingual biodata can help when the candidate is comfortable in English but parents or relatives prefer an Indian language. The goal is not to duplicate every sentence; it is to make the key profile information understandable to both audiences.',
    quickAnswer: 'Use English for shared professional terms when useful and provide regional-language labels or content for the sections families need to read. Keep names, dates and locations consistent between versions and proofread both scripts before exporting.',
    sections: [
      { heading: 'Choose the right level of translation', paragraphs: ['Field labels are often the most important part to translate: date of birth, height, education, occupation, family and expectations. A long bilingual paragraph can make the document crowded, so translate only the content that helps the intended reader.', 'For professional roles or company names, keeping the official English spelling can be more accurate than transliterating it.'] },
      { heading: 'Regional scripts need real space', paragraphs: ['Indian scripts can have different line lengths and shaping behaviour. A field that fits in English may wrap in Gujarati, Hindi, Marathi or another script. A premium builder should let the user preview the actual output instead of assuming one fixed width.', 'Use a script-aware font and check the PDF after export.'] },
      { heading: 'Useful for families across cities and countries', paragraphs: ['Bilingual profiles can be particularly helpful for NRI families or households where one generation reads English more comfortably and another prefers a regional language.', 'Keep the same facts in both languages. If one version says a different city, qualification or date, the confusion can undermine the profile.'] },
    ],
    checklist: ['Choose two readable languages', 'Keep facts consistent', 'Use script-aware typography', 'Avoid unnecessary duplicate paragraphs', 'Preview on mobile', 'Check PDF and Word exports'],
    related: [{ href: '/urdu-biodata-for-marriage', label: 'Urdu biodata' }, { href: '/hindi-marriage-biodata', label: 'Hindi format' }, { href: '/gujarati-marriage-biodata', label: 'Gujarati format' }, { href: '/create', label: 'Build a bilingual profile' }],
    faqs: [
      { question: 'What does bilingual biodata mean?', answer: 'It means the key information is presented so that people using two languages can understand the profile, often English plus a regional Indian language.' },
      { question: 'Will bilingual text make the biodata too long?', answer: 'It can if every sentence is duplicated. Keep field labels and important profile information concise and use a separate section when a full translation is needed.' },
      { question: 'Can I export bilingual text to PDF?', answer: 'Yes. The PDF workflow is designed to preserve selectable text and Indian-script typography.' },
      { question: 'Which languages can I use?', answer: 'The project supports several Indian scripts and language labels; choose the combination that your family can proofread confidently.' },
    ],
  },
  {
    path: '/about-myself-for-marriage-biodata', title: 'About Myself for Marriage Biodata | Examples', updatedAt: '2026-10-08',
    description: 'Learn how to write an About Myself section for a marriage biodata with concise, natural examples for bride and groom profiles.',
    eyebrow: 'About Me guide',
    intro: 'The About Myself section should sound like a person speaking about their life, not like a list of adjectives. A short paragraph can show personality, work, family values and the kind of life you enjoy.',
    quickAnswer: 'A good About Myself paragraph is usually 3–5 sentences. Mention what you do, a few genuine interests, how you spend your time and one or two values that matter to you. Avoid generic phrases unless you explain them with a real detail.',
    sections: [
      { heading: 'A useful structure', paragraphs: ['Start with the present: education or work and where you live. Then add two or three personal details such as reading, fitness, travel, music, cooking, volunteering or time with family. Finish with a value or lifestyle preference that helps someone understand you.', 'Example: “I work as a software developer in Ahmedabad and enjoy building small side projects. Outside work I like cricket, weekend road trips and cooking with my family. I value a calm home life and would like to continue growing professionally after marriage.”'] },
      { heading: 'Write for a real conversation', paragraphs: ['The best profile summary gives another person an easy opening for conversation. If you enjoy classical music, mention what you listen to. If you travel, mention the kind of places you like. Specific details feel more credible than “I am simple, caring and down to earth.”', 'Do not turn About Me into a second résumé. Education and job details already have their own section.'] },
      { heading: 'What to avoid', paragraphs: ['Avoid exaggerated claims, copied lines, jokes that could be misunderstood and statements that describe other people rather than yourself. Keep the tone positive without presenting an unrealistic picture.', 'If the profile is being prepared by parents, make sure the candidate agrees with the wording. The person should recognise themselves in the final paragraph.'] },
    ],
    checklist: ['3–5 sentences', 'Present work or education', 'Two or three genuine interests', 'One or two values', 'Natural language', 'Candidate-approved wording'],
    related: [{ href: '/marriage-biodata-profile-summary-examples', label: 'Profile summary examples' }, { href: '/partner-expectations-for-marriage-biodata', label: 'Partner expectations' }, { href: '/biodata-for-marriage-boy', label: 'Boy biodata' }, { href: '/biodata-for-marriage-girl', label: 'Girl biodata' }],
    faqs: [
      { question: 'How long should About Myself be?', answer: 'Three to five sentences is enough for most biodatas. The goal is personality and context, not a full autobiography.' },
      { question: 'What should I write about myself for a marriage biodata?', answer: 'Mention your present work or education, genuine interests, lifestyle and a few values that matter to you.' },
      { question: 'Should parents write the About Me section?', answer: 'They can draft it, but the candidate should approve the final wording because the section represents their personality.' },
      { question: 'Can I use examples?', answer: 'Yes, but adapt them to your actual life rather than copying a generic paragraph.' },
    ],
  },
  {
    path: '/partner-expectations-for-marriage-biodata', title: 'Partner Expectations for Marriage Biodata | Guide', updatedAt: '2026-10-08',
    description: 'Learn how to write partner expectations for a marriage biodata with respectful, specific examples that invite a real conversation.',
    eyebrow: 'Expectations guide',
    intro: 'Partner expectations should communicate what matters without sounding like a job description. A good section tells the reader about values, location, career or family preferences that genuinely affect compatibility.',
    quickAnswer: 'Write 2–4 sentences covering the qualities, lifestyle or practical arrangements that matter most. Be clear about important boundaries, but avoid an exhaustive checklist of appearance, salary, caste, location and personality requirements.',
    sections: [
      { heading: 'Choose the few things that really matter', paragraphs: ['Think about values first: respect, communication, family involvement, career support, lifestyle, faith or location. If you are open to relocation or an NRI match, say so. If staying near parents is important, say that too.', 'The goal is not to eliminate every possible mismatch in one paragraph. It is to help another family understand whether a conversation makes sense.'] },
      { heading: 'Examples for different situations', paragraphs: ['A general example: “Looking for a kind, educated partner who values family and open communication. I am happy to relocate for the right opportunity and would like both partners to support each other’s careers.”', 'An NRI example: “Open to a partner living in India or abroad. Comfortable discussing relocation after marriage, with career plans considered for both sides.”'] },
      { heading: 'What makes expectations feel respectful', paragraphs: ['Describe your own needs rather than judging other people. “I would like a partner who supports continued work” is clearer than “No conservative family.” “Prefer a city-based lifestyle” is more useful than a long list of places you refuse to live.', 'If a community or religious preference is genuinely important, state it honestly and respectfully. Do not use coded language that could be misunderstood.'] },
    ],
    checklist: ['2–4 sentences', 'Values before superficial criteria', 'Location and career preferences when relevant', 'Respectful language', 'Honest flexibility', 'Candidate-approved wording'],
    related: [{ href: '/about-myself-for-marriage-biodata', label: 'About Myself guide' }, { href: '/blog/what-to-write-in-partner-expectations', label: 'Expectations examples' }, { href: '/marriage-biodata-format', label: 'General biodata guide' }, { href: '/create', label: 'Write your expectations' }],
    faqs: [
      { question: 'How long should partner expectations be?', answer: 'Usually two to four sentences. A short, clear section is easier to read and leaves room for a real conversation.' },
      { question: 'Should I mention salary expectations?', answer: 'If financial compatibility is important, describe the broader lifestyle or career context rather than turning the biodata into a negotiation document.' },
      { question: 'Can I mention relocation?', answer: 'Yes. Location and relocation can be important practical compatibility factors.' },
      { question: 'Should parents write the expectations?', answer: 'They can contribute, but the candidate should approve the final version so it reflects the person’s own preferences.' },
    ],
  },
  {
    path: '/family-details-in-marriage-biodata', title: 'Family Details in Marriage Biodata | What to Include', updatedAt: '2026-10-08',
    description: 'Learn what family details to include in a marriage biodata: parents, siblings, native place, family type and optional community fields.',
    eyebrow: 'Family section guide',
    intro: 'Family details help a matrimonial reader understand the person’s background, but the section should stay factual and privacy-conscious. A short list of parents, siblings and family context is usually more useful than a long description of status or assets.',
    quickAnswer: 'Include parents’ names and occupations, siblings, family type, family status when relevant, native place and any community or lineage fields your family actually uses. Avoid publishing detailed addresses, identity numbers or private financial information.',
    sections: [
      { heading: 'Parents and siblings', paragraphs: ['Parents’ names and occupations are common. For siblings, mention number and broad status such as married/unmarried when that is relevant to your family’s usual biodata practice. Do not include phone numbers or private details about siblings unless they have agreed.', 'If a parent is retired, self-employed or deceased, use accurate and respectful wording. The family section should not hide important current responsibilities.'] },
      { heading: 'Family type, status and native place', paragraphs: ['Nuclear, joint or another accurate description can help set expectations about household arrangements. Native place can be useful when the family has strong ancestral roots even if everyone now lives in a different city.', 'Avoid vague claims such as “high-status family” when a simple factual description is more useful. Education, occupations and the family’s current city usually provide enough context.'] },
      { heading: 'Community fields are optional', paragraphs: ['Gotra, caste, sub-caste, kuldevi, devak, mosal, pravar or other community-specific details can be important for some families. They should not be treated as universal requirements.', 'Use the exact terminology your family uses. If you are unsure about a traditional field, ask an elder rather than selecting a value because it appears in another biodata.'] },
    ],
    checklist: ['Parents and occupations', 'Siblings and broad status', 'Family type when useful', 'Native place', 'Verified community fields', 'No unnecessary private identifiers'],
    related: [{ href: '/marriage-biodata-format', label: 'Core format' }, { href: '/marriage-biodata-formats-by-community', label: 'Community formats' }, { href: '/gujarati-marriage-biodata', label: 'Gujarati fields' }, { href: '/marathi-marriage-biodata', label: 'Marathi fields' }],
    faqs: [
      { question: 'What family details are normally included?', answer: 'Parents, occupations, siblings, family type, native place and selected community fields are common. Include only information the family is comfortable sharing.' },
      { question: 'Should family income or assets be listed?', answer: 'Usually a concise occupation or business description is enough for a first biodata. Detailed financial records do not belong in a broadly shared profile.' },
      { question: 'Should siblings’ phone numbers be included?', answer: 'No, not unless there is a specific reason and the sibling has agreed. Use one appropriate family contact.' },
      { question: 'Can I add a community-specific field?', answer: 'Yes. The builder supports custom fields in addition to predefined community presets.' },
    ],
  },
  {
    path: '/marriage-biodata-profile-summary-examples', title: 'Marriage Biodata Profile Summary | Bride & Groom', updatedAt: '2026-10-08',
    description: 'Practical marriage biodata profile summary examples for bride and groom profiles, with guidance to personalise each paragraph.',
    eyebrow: 'Profile writing guide',
    intro: 'A profile summary sits between a résumé and a personal introduction. It should quickly explain who the person is today and give a reader enough personality to decide whether to start a conversation.',
    quickAnswer: 'A strong marriage biodata profile summary combines present work or education, a few genuine interests, family or lifestyle context and a positive statement about what the person values. Keep it short enough to read on a phone.',
    sections: [
      { heading: 'Groom summary example', paragraphs: ['“I work as a product designer in Bengaluru and enjoy the mix of creativity and technology in my work. Outside the office I like cricket, photography and weekend trips with friends and family. I value close family relationships, a balanced lifestyle and continued growth in my career.”', 'This works because it gives occupation, city, interests and values without claiming to be perfect. Replace every detail with the person’s actual life.'] },
      { heading: 'Bride summary example', paragraphs: ['“I am a finance professional based in Pune and enjoy reading, classical music and trying new recipes. I am close to my family and value open communication, independence and a calm home environment. I would like to continue working after marriage and am open to discussing relocation together.”', 'Again, the useful part is specificity. A reader can imagine what everyday life might look like and knows what topics to discuss next.'] },
      { heading: 'Avoid generic copy', paragraphs: ['Phrases such as “simple, sober, beautiful, cultured and family-oriented” are common but tell the reader very little. Replace them with one concrete example of what those values mean in your life.', 'A profile summary is also not the place to repeat every field. Let the structured sections handle date of birth, height, education and occupation.'] },
    ],
    checklist: ['3–5 sentences', 'Current work or education', 'Specific interests', 'Real values', 'Optional career/location expectation', 'Candidate-approved wording'],
    related: [{ href: '/about-myself-for-marriage-biodata', label: 'About Myself guide' }, { href: '/partner-expectations-for-marriage-biodata', label: 'Expectations guide' }, { href: '/biodata-for-marriage-boy', label: 'Groom biodata' }, { href: '/biodata-for-marriage-girl', label: 'Bride biodata' }],
    faqs: [
      { question: 'How long should a marriage biodata profile summary be?', answer: 'Three to five sentences is usually enough. Keep it specific and easy to read on a phone.' },
      { question: 'Can I copy an example?', answer: 'Use examples as a structure, not as final copy. The summary should describe the actual person.' },
      { question: 'Should the summary mention salary?', answer: 'Usually the structured career section is a better place for income. The summary should focus on personality and lifestyle.' },
      { question: 'Can parents write the summary?', answer: 'They can help draft it, but the candidate should approve the wording.' },
    ],
  },
  {
    path: '/royal-wedding-biodata-format', title: 'Royal Wedding Biodata Format | Elegant Indian Style', updatedAt: '2026-10-08',
    description: 'Explore a royal wedding biodata format with rich visual hierarchy, traditional motifs and a readable Indian marriage profile.',
    eyebrow: 'Design guide',
    intro: 'A royal wedding biodata format can use deeper colours, ornamental motifs and traditional typography without turning the page into a poster. The information should remain the visual priority.',
    quickAnswer: 'Use a restrained royal palette, one strong portrait, clear section headings and enough whitespace around family and career details. Decorative elements should frame the information rather than compete with it.',
    sections: [
      { heading: 'What makes a royal design work', paragraphs: ['Royal styling usually comes from proportion and restraint rather than adding more ornaments. A deep colour, metallic accent, subtle border or traditional motif can establish the mood while keeping text readable.', 'If the template uses a religious symbol, let the user select the symbol appropriate to their family rather than hard-coding one into every profile.'] },
      { heading: 'Traditional information can remain optional', paragraphs: ['Gotra, kuldevi, devak, horoscope details or community fields can be added when relevant. A royal visual style does not mean every traditional field needs to appear.', 'Keep education and career easy to scan. The profile should still work for a reader who has never seen the family’s preferred traditional format.'] },
      { heading: 'Print and mobile checks', paragraphs: ['Rich backgrounds can look different on different printers. Test the PDF before sending it to a local printer and check that small text remains readable on a phone.', 'Additional photos are better placed on dedicated pages if the family wants a larger gallery.'] },
    ],
    checklist: ['Restrained royal palette', 'Readable typography', 'One strong profile photo', 'Optional cultural fields', 'Print test', 'Separate photo pages when needed'],
    related: [{ href: '/traditional-marriage-biodata-template', label: 'Traditional template' }, { href: '/modern-marriage-biodata-format', label: 'Modern format' }, { href: '/templates', label: 'Template gallery' }, { href: '/create', label: 'Create a royal-style biodata' }],
    faqs: [
      { question: 'What makes a biodata look royal?', answer: 'A restrained rich palette, elegant typography, proportionate ornaments and strong information hierarchy.' },
      { question: 'Should royal biodatas include more fields?', answer: 'Not necessarily. Visual style and information quantity are separate decisions.' },
      { question: 'Can I use a religious symbol?', answer: 'Yes, when it reflects the user’s own family preference and the chosen template supports it.' },
      { question: 'Will a royal design print well?', answer: 'It can, but always check a PDF print preview and make sure text contrast remains strong.' },
    ],
  },
  {
    path: '/traditional-marriage-biodata-template', title: 'Traditional Marriage Biodata Template | Family Format', updatedAt: '2026-10-08',
    description: 'Create a traditional marriage biodata template with family, lineage, horoscope and career fields that remain optional and editable.',
    eyebrow: 'Traditional format',
    intro: 'Traditional marriage biodata templates often include family background, lineage and horoscope information alongside personal and career details. A modern builder can preserve that familiar structure while letting users remove fields that do not apply.',
    quickAnswer: 'A traditional Indian biodata commonly combines personal details, parents and siblings, education, occupation, native place and optional community or horoscope fields. Keep the terminology accurate to the family rather than assuming one tradition fits everyone.',
    sections: [
      { heading: 'Traditional does not have to mean crowded', paragraphs: ['Use familiar section names and motifs but keep each field concise. A traditional format can still use whitespace and a clean grid so parents and relatives can scan it quickly.', 'Religious symbols and community-specific headers should be user-selectable. Hindu/Jain, Muslim, Sikh and Christian families can choose different visual treatments without changing the core information architecture.'] },
      { heading: 'Lineage and horoscope fields', paragraphs: ['Gotra, kuldevi, devak, pravar, rashi, nakshatra and manglik status may be relevant to some households. Add them only when the family actually uses them and verify the values before sharing.', 'If a separate kundali is prepared, the biodata can carry a short summary instead of reproducing the entire chart.'] },
      { heading: 'A traditional profile still needs personality', paragraphs: ['Education, work, hobbies and expectations help the reader understand the person rather than only the family. A short About Me section can modernise the format without removing its traditional character.', 'Use a clear profile photo and keep extra photos separate if they are needed.'] },
    ],
    checklist: ['Traditional section hierarchy', 'Verified lineage fields', 'Optional horoscope information', 'Education and career', 'Short About Me', 'Clear photo and contact details'],
    related: [{ href: '/kundali-marriage-biodata-format', label: 'Kundali fields' }, { href: '/royal-wedding-biodata-format', label: 'Royal style' }, { href: '/marriage-biodata-formats-by-community', label: 'Community formats' }, { href: '/create', label: 'Create a traditional biodata' }],
    faqs: [
      { question: 'What belongs in a traditional marriage biodata?', answer: 'Personal, family, education, career and optional lineage or horoscope details. The exact fields depend on family practice.' },
      { question: 'Can I remove modern fields I do not need?', answer: 'Yes. Fields can be hidden, reordered or extended with custom fields.' },
      { question: 'Can traditional templates use religious symbols?', answer: 'Yes. The symbol should be selected according to the user’s own religious or family preference.' },
      { question: 'Can a traditional biodata be one page?', answer: 'Yes, when the content is concise. If additional information needs space, a second page is better than tiny text.' },
    ],
  },
  {
    path: '/single-page-marriage-biodata-format', title: 'Single Page Marriage Biodata | A4 Format Guide', updatedAt: '2026-10-08',
    description: 'Create a readable single-page marriage biodata format in A4 with concise fields, profile photo and optional extra photo pages.',
    eyebrow: 'One-page format',
    intro: 'A single-page marriage biodata is ideal for first introductions when the profile can fit comfortably without tiny text. The key is editing the information, not simply shrinking the entire page.',
    quickAnswer: 'Prioritise personal details, family, education and career, About Me, expectations and contact. Remove low-value fields and keep the profile photo prominent. If more photos are needed, put them on separate pages rather than shrinking the main biodata.',
    sections: [
      { heading: 'What to keep on page one', paragraphs: ['Keep the first page focused on information that helps a family decide whether to continue the conversation. Personal facts, family background, education, career and a short personal section normally fit when values are concise.', 'Use optional fields only when they matter. A one-page format is not a competition to include every possible field.'] },
      { heading: 'Design around real text', paragraphs: ['Long names, regional scripts and career descriptions can change the height of a row. Preview the actual data before exporting and make sure values wrap inside their containers.', 'If the content genuinely cannot fit without becoming hard to read, use a second page. A readable two-page document is better than a one-page document that requires zooming.'] },
      { heading: 'Separate photos when needed', paragraphs: ['The profile photo can stay on page one. Additional photos can be placed on dedicated pages or collected on one gallery page. This gives families a clean way to share more images without damaging the main layout.', 'For WhatsApp, the page-by-page image export can be more useful than sending a tiny contact sheet.'] },
    ],
    checklist: ['A4 portrait', 'Concise values', 'Profile photo on page one', 'Optional fields removed when unnecessary', 'Readable regional scripts', 'Separate additional-photo pages'],
    related: [{ href: '/marriage-biodata-format-pdf', label: 'PDF guide' }, { href: '/simple-marriage-biodata-format', label: 'Simple format' }, { href: '/marriage-biodata-format-pdf', label: 'One-page maker' }, { href: '/create', label: 'Create a one-page biodata' }],
    faqs: [
      { question: 'Can all marriage biodatas fit on one page?', answer: 'Many can, but not all. The right choice is to keep the text readable and use a second page when the content genuinely needs more room.' },
      { question: 'How do I fit more fields?', answer: 'Remove low-value fields, shorten values and reorder the most important information first. Do not reduce the font until it becomes difficult to read.' },
      { question: 'Can extra photos be separate pages?', answer: 'Yes. Additional photos can be displayed as dedicated pages or on a gallery page.' },
      { question: 'Is A4 one-page biodata good for printing?', answer: 'Yes, provided the content has enough whitespace and the text remains readable at normal print size.' },
    ],
  },
  {
    path: '/biodata-maker-for-mobile', title: 'Biodata Maker for Mobile | Create on Phone', updatedAt: '2026-10-08',
    description: 'Create a marriage biodata on your phone with a mobile-friendly builder, photo upload, live preview and PDF or Word export.',
    eyebrow: 'Mobile workflow',
    intro: 'Many marriage biodatas are created and shared on phones. A mobile-first workflow should make typing, photo selection, previewing and exporting practical without forcing users to manage a desktop design application.',
    quickAnswer: 'Open the builder in a modern mobile browser, complete the predefined fields, add a profile photo, preview the selected template and export the finished biodata. Keep the first page concise and use dedicated photo pages when more images are needed.',
    sections: [
      { heading: 'Fill only what matters first', paragraphs: ['Phone screens make long forms feel heavier, so start with the core fields. Optional community, horoscope and NRI details can be added later when they are actually needed.', 'Use the field reorder controls to bring the information your family cares about to the top of each category.'] },
      { heading: 'Photo handling on a phone', paragraphs: ['Choose a recent profile photo from the device and crop it to fit the template. Additional photos can be uploaded when needed, but the main page should remain focused on one profile image.', 'If the family wants to share several photos, use the dedicated photo-page export rather than placing tiny thumbnails in the main biodata.'] },
      { heading: 'Mobile sharing and app searches', paragraphs: ['A PNG can be convenient for WhatsApp and social sharing, while a PDF is better for printing or formal forwarding. Word export is useful when a family member wants to make later text edits on a computer.', 'If you are searching for a bio data maker app download, a marriage biodata maker APK or an online bio data maker on phone, a browser-based workflow avoids installing an APK and keeps the same profile accessible from a supported mobile browser. If you are comparing a biodata maker app without ads with a browser tool, compare the actual export quality, privacy model and editing controls rather than the app label alone. Always preview the exported document before sending it and check regional scripts and long values for wrapping.'] },
    ],
    checklist: ['Use a modern mobile browser', 'Complete core fields first', 'Upload one strong profile photo', 'Preview long text', 'Choose PDF or image sharing', 'Keep a downloaded backup'],
    related: [{ href: '/biodata-maker-for-whatsapp', label: 'WhatsApp sharing' }, { href: '/marriage-biodata-maker-online', label: 'No-login maker' }, { href: '/biodata-maker-with-photo', label: 'Photo biodata maker' }, { href: '/create', label: 'Open on your phone' }],
    faqs: [
      { question: 'Can I make a biodata entirely on my phone?', answer: 'Yes. The builder is designed to work in a modern mobile browser, including photo selection and export.' },
      { question: 'Can I download the PDF on my phone?', answer: 'Yes. The browser print flow can save the A4 document as a PDF.' },
      { question: 'Can I share the biodata on WhatsApp?', answer: 'Yes. The image sharing flow is designed for quick WhatsApp use when supported by the device.' },
      { question: 'Can I add five photos from my phone?', answer: 'Yes. The photo system supports a profile photo plus additional photos, with page options for the extra images.' },
    ],
  },
  {
    path: '/biodata-maker-for-whatsapp', title: 'Biodata Maker for WhatsApp | Photo & PDF', updatedAt: '2026-10-08',
    description: 'Create a marriage biodata for WhatsApp with a clean image export, A4 PDF and optional separate photo pages that are easy to review on a phone.',
    eyebrow: 'WhatsApp sharing',
    intro: 'WhatsApp is often where a marriage biodata first travels between relatives. A good export should remain readable after forwarding and should not expose more personal information than the family intends to share.',
    quickAnswer: 'Use a clean PNG when the recipient wants an image that opens immediately, or send the A4 PDF when printing and text quality matter. Keep the first biodata page focused and move extra photos to dedicated pages when needed.',
    sections: [
      { heading: 'Image versus PDF on WhatsApp', paragraphs: ['PNG is convenient for quick viewing and status-style sharing. PDF is better when the recipient may print the document or needs selectable text. If the family uses both, create a consistent pair from the same profile.', 'Avoid screenshots of the browser editor. Export only the clean biodata page so controls, scrollbars and empty canvas areas never appear in the shared image.'] },
      { heading: 'Privacy before forwarding', paragraphs: ['A biodata can travel farther than expected. Consider whether the first-share version needs a full address or direct phone number. City and state may be enough until both families decide to continue.', 'Keep children’s details, workplace-sensitive information and identity-document data out of a broadly forwarded copy unless there is a specific reason to share them.'] },
      { heading: 'Additional photos', paragraphs: ['If a family wants more than the profile portrait, choose the photo-page option that matches the sharing context. One photo per page creates large, clear images; an all-photos page creates a compact gallery.', 'This keeps the main biodata readable while still making it easy to send more photos.'] },
    ],
    checklist: ['Export the clean page, not the editor', 'Use PNG for quick viewing', 'Use PDF for printing', 'Keep contact details appropriate', 'Choose a photo-page layout', 'Preview before forwarding'],
    related: [{ href: '/biodata-maker-for-mobile', label: 'Mobile maker' }, { href: '/marriage-biodata-format-pdf', label: 'PDF guide' }, { href: '/biodata-maker-with-photo', label: 'Photo maker' }, { href: '/create', label: 'Create and share' }],
    faqs: [
      { question: 'What is the best biodata format for WhatsApp?', answer: 'A clean single-page image is convenient for quick viewing, while a PDF is better for printing and formal sharing.' },
      { question: 'Can I share multiple photos?', answer: 'Yes. Additional photos can be exported as separate pages or as one gallery page.' },
      { question: 'Should I share my full address on WhatsApp?', answer: 'Usually not in the first broadly forwarded version. City and state are often sufficient.' },
      { question: 'Can I send both PDF and image?', answer: 'Yes. They serve different purposes and can be generated from the same profile.' },
    ],
  },
  {
    path: '/biodata-maker-with-photo', title: 'Biodata Maker with Photo | Profile + 5 Images', updatedAt: '2026-10-08',
    description: 'Create a marriage biodata with a profile photo and up to five images, including dedicated photo pages for larger sharing.',
    eyebrow: 'Photo biodata maker',
    intro: 'A marriage biodata with photo should make the main portrait part of the information hierarchy, not an afterthought. Additional photos can provide variety without crowding the first page.',
    quickAnswer: 'Use one photo as the profile image and add additional photos only when they genuinely help. The builder supports up to five images and can place the extra photos on dedicated pages or together on a gallery page.',
    sections: [
      { heading: 'Choose the profile photo carefully', paragraphs: ['Use a recent, clear portrait with natural lighting. The face should be easy to see and the crop should work with the chosen template. Avoid heavy filters that make the person look unlike their everyday appearance.', 'The profile photo stays with the main biodata page. Additional photos can be separated so the information remains readable.'] },
      { heading: 'Five photos without a crowded page', paragraphs: ['The photo system supports up to five images. That does not mean all five need to appear as tiny thumbnails on page one. A page-per-photo option gives each additional image more space, while an all-photos option creates a compact gallery page.', 'Choose based on how the document will be shared. A print-oriented profile may benefit from dedicated pages; a quick WhatsApp share may prefer a compact gallery.'] },
      { heading: 'Photo privacy', paragraphs: ['Only upload photos you are comfortable placing in the exported document. Avoid images that reveal another person’s private information, workplace screens or home address.', 'Before forwarding the finished biodata, check every photo page as carefully as the main page.'] },
    ],
    checklist: ['One clear profile photo', 'Up to five total images', 'Correct crop', 'Separate photo-page option', 'No private background information', 'Preview every export page'],
    related: [{ href: '/biodata-maker-for-whatsapp', label: 'WhatsApp sharing' }, { href: '/marriage-biodata-format-pdf', label: 'PDF guide' }, { href: '/single-page-marriage-biodata-format', label: 'One-page format' }, { href: '/create', label: 'Upload photos' }],
    faqs: [
      { question: 'How many photos can I add?', answer: 'The current builder supports up to five photos, including the profile photo.' },
      { question: 'Can I change which photo is the profile photo?', answer: 'Yes. You can choose another uploaded image as the profile photo.' },
      { question: 'Can additional photos be separate pages?', answer: 'Yes. You can use one-photo-per-page or an all-photos gallery page.' },
      { question: 'Should all five photos be on the first page?', answer: 'No. Keeping one profile photo on page one usually gives the main biodata a cleaner hierarchy.' },
    ],
  },

  {
    path: '/maratha-biodata-format', title: 'Maratha Marriage Biodata Format | Family & Career', updatedAt: '2026-10-08',
    description: 'Create a Maratha marriage biodata format with family, education, career, optional lineage details and a polished A4 layout.',
    eyebrow: 'Community format', intro: 'A Maratha marriage biodata can combine family roots and community information with a clear modern profile of education, career and expectations. Practices differ by family, so optional fields should remain user-controlled.',
    quickAnswer: 'A practical Maratha biodata includes personal details, parents and siblings, education, occupation, native place, About Me and expectations. Add gotra, family traditions or other community fields only when your family actually uses them.',
    sections: [
      { heading: 'Family background without assumptions', paragraphs: ['Native place, parents’ occupations and siblings can provide useful context. If a family uses a specific lineage or traditional field, include the exact value confirmed by the household rather than copying another profile.', 'Community identity is important to some families and less important to others. The document should reflect the candidate and family rather than a generic stereotype.'] },
      { heading: 'Education and career stay prominent', paragraphs: ['Qualification, occupation, designation and work city should remain easy to scan. If the candidate runs a family business, describe the actual activity briefly instead of using only the word “business”.', 'For an NRI or inter-city profile, add country or city and relocation expectations when useful. Avoid private employer or identity details.'] },
      { heading: 'Modern sharing', paragraphs: ['A clear profile photo, concise About Me and practical expectations make the profile easier to forward. Keep the first version privacy-conscious and use the PDF or Word export that matches the family’s workflow.', 'If traditional fields matter, they can sit alongside modern career details without taking over the entire page.'] },
    ],
    checklist: ['Family and native place', 'Education and career', 'Optional community fields', 'About Me', 'Expectations', 'Profile photo and safe contact'],
    related: [{ href: '/marriage-biodata-format', label: 'Core marriage format' }, { href: '/hindu-marriage-biodata-format', label: 'Hindu biodata' }, { href: '/traditional-marriage-biodata-template', label: 'Traditional template' }, { href: '/create', label: 'Create a Maratha biodata' }],
    faqs: [
      { question: 'What should a Maratha marriage biodata include?', answer: 'Personal details, family background, education, career, native place, About Me and expectations are a useful base. Community-specific fields are optional.' },
      { question: 'Should every Maratha biodata use the same fields?', answer: 'No. Family practices vary, so optional fields should be selected by the user.' },
      { question: 'Can I add a custom community field?', answer: 'Yes. Custom fields can be added when the predefined fields do not cover a family-specific need.' },
      { question: 'Can I export it to PDF?', answer: 'Yes. The builder supports A4 PDF export.' },
    ],
  },
  {
    path: '/brahmin-biodata-format-for-marriage', title: 'Brahmin Biodata Format | Gotra, Pravar & Career', updatedAt: '2026-10-08',
    description: 'Create a Brahmin biodata format for marriage with optional gotra, pravar, rashi, nakshatra, education and career fields.',
    eyebrow: 'Community format', intro: 'A Brahmin marriage biodata may include lineage and horoscope information that a family uses during introductions. Because Brahmin communities and family practices differ, those fields should be verified and optional rather than guessed.',
    quickAnswer: 'A Brahmin marriage biodata can include gotra and pravar when verified, along with birth details, rashi or nakshatra if the family uses them. Keep education, career, family and personality sections equally visible.',
    sections: [
      { heading: 'Verify lineage fields', paragraphs: ['Gotra and pravar are details that should come from the family’s own records or an informed elder. Do not infer them from surname or location. If a family does not use pravar, leave it out.', 'Birth date, time and place can be useful when a separate kundali is prepared. If the time is uncertain, record that uncertainty instead of inventing precision.'] },
      { heading: 'Keep the person at the centre', paragraphs: ['Education, career, current city, hobbies and expectations help a reader understand the person beyond lineage. A modern Brahmin biodata can retain traditional fields without becoming a horoscope sheet.', 'For working professionals or NRI candidates, occupation and location may be especially useful in the first introduction.'] },
      { heading: 'Respectful optionality', paragraphs: ['Different families have different practices around caste, sub-caste, rituals and matching. A good builder lets the user remove fields that do not apply and add a custom field when a family uses another term.', 'This makes the format useful across different Brahmin traditions without pretending they are identical.'] },
    ],
    checklist: ['Verified gotra', 'Pravar only when relevant and known', 'Birth details', 'Education and career', 'Family details', 'Optional horoscope fields'],
    related: [{ href: '/kundali-marriage-biodata-format', label: 'Kundali format' }, { href: '/traditional-marriage-biodata-template', label: 'Traditional template' }, { href: '/hindu-marriage-biodata-format', label: 'Hindu biodata' }, { href: '/create', label: 'Create a Brahmin biodata' }],
    faqs: [
      { question: 'Should every Brahmin biodata include pravar?', answer: 'No. Include it when the family uses it and has verified the value.' },
      { question: 'Can gotra be inferred from surname?', answer: 'It should not be guessed from surname. Use the family’s verified information.' },
      { question: 'Can horoscope fields be removed?', answer: 'Yes. They are optional and depend on the family’s practice.' },
      { question: 'Can the profile still look modern?', answer: 'Yes. Traditional fields and modern information hierarchy can coexist.' },
    ],
  },
  {
    path: '/rajput-marriage-biodata-format', title: 'Rajput Marriage Biodata Format | Traditional & Modern', updatedAt: '2026-10-08',
    description: 'Create a Rajput marriage biodata format with family background, native place, education, career and optional community fields.',
    eyebrow: 'Community format', intro: 'A Rajput marriage biodata can carry a strong sense of family background while still presenting the candidate’s education, career and personality clearly. The exact fields should follow the family rather than a generic community checklist.',
    quickAnswer: 'Use personal details, family background, native place, education, career, About Me and expectations as the core. Add lineage, clan or other community-specific details only when the family has confirmed the terminology and wants it included.',
    sections: [
      { heading: 'Family and roots', paragraphs: ['Native place and family background can be meaningful in a Rajput matrimonial introduction. Describe them factually and avoid exaggerated status claims. Parents’ occupations and siblings provide useful context without turning the biodata into a family history.', 'If a family uses a specific clan, lineage or traditional field, verify the exact term and spelling before publishing.'] },
      { heading: 'Education, work and lifestyle', paragraphs: ['A contemporary profile should make education and career easy to scan. Current city, occupation and work location can matter as much as family roots when two families are considering practical compatibility.', 'Use About Me to describe hobbies, interests and lifestyle. This gives a more complete picture than a list of family credentials.'] },
      { heading: 'Traditional visual language', paragraphs: ['A traditional or royal visual treatment can work well when it remains readable. Decorative symbols should be optional and selected by the user, not assumed from a surname or community label.', 'Additional photos can be kept on dedicated pages so the main biodata remains clean.'] },
    ],
    checklist: ['Verified family terminology', 'Native place', 'Education and career', 'Lifestyle and hobbies', 'Expectations', 'Optional traditional styling'],
    related: [{ href: '/royal-wedding-biodata-format', label: 'Royal wedding format' }, { href: '/traditional-marriage-biodata-template', label: 'Traditional template' }, { href: '/marriage-biodata-format', label: 'Core format' }, { href: '/create', label: 'Create a Rajput biodata' }],
    faqs: [
      { question: 'What should a Rajput marriage biodata include?', answer: 'Personal, family, native-place, education, career and expectations are a practical base. Community-specific lineage fields can be added when verified.' },
      { question: 'Should family status claims be included?', answer: 'Factual family and occupation information is more useful than exaggerated status language.' },
      { question: 'Can I use a royal design?', answer: 'Yes. A royal visual style can be selected while keeping the information hierarchy clear.' },
      { question: 'Can I add custom family fields?', answer: 'Yes. Custom fields are available when a family needs information beyond the predefined structure.' },
    ],
  },
  {
    path: '/anand-karaj-biodata-format', title: 'Anand Karaj Biodata Format | Sikh Marriage Profile', updatedAt: '2026-10-08',
    description: 'Create an Anand Karaj marriage biodata with Sikh family, education and career details plus optional faith-related fields for a respectful profile.',
    eyebrow: 'Sikh marriage format', intro: 'An Anand Karaj biodata can keep the practical structure of a marriage profile while allowing Sikh families to include faith, family and community details that matter to them. The exact fields should be chosen by the family.',
    quickAnswer: 'Start with personal, family, education and career information. Add Sikh faith or community details when they are relevant to the family, and keep the profile focused on the person rather than turning it into a ceremonial document.',
    sections: [
      { heading: 'A Sikh-friendly structure', paragraphs: ['The core profile can include parents, siblings, education, occupation, current city, hobbies and expectations. Family members can add faith-related preferences or other community information when they consider it important.', 'Do not assume every Sikh family follows the same matrimonial checklist. Keep optional fields under the user’s control.'] },
      { heading: 'Respectful religious presentation', paragraphs: ['The builder can offer a Khanda or Ik Onkar style header symbol as an optional visual choice. The user should decide whether to include a symbol and which one fits their preference.', 'Keep the visual treatment respectful and avoid decorative use that could be inappropriate for the family.'] },
      { heading: 'Modern compatibility details', paragraphs: ['Career, city, relocation plans, lifestyle and expectations are practical parts of a current profile. A short About Me can show how the person spends time outside work and what values matter to them.', 'For overseas candidates, country and residency status can be included without publishing document numbers.'] },
    ],
    checklist: ['Personal and family details', 'Education and career', 'Optional Sikh/community fields', 'Respectful header symbol if desired', 'About Me and expectations', 'Privacy-safe contact'],
    related: [{ href: '/sikh-marriage-biodata', label: 'Sikh marriage biodata' }, { href: '/marriage-biodata-format', label: 'General profile' }, { href: '/marriage-biodata-format-pdf', label: 'PDF guide' }, { href: '/create', label: 'Create an Anand Karaj biodata' }],
    faqs: [
      { question: 'Is an Anand Karaj biodata different from a Sikh marriage biodata?', answer: 'They can use the same practical profile structure. The wording and optional faith-related fields can be tailored to the family.' },
      { question: 'Can I add a Khanda or Ik Onkar symbol?', answer: 'Yes, where the selected template supports the community symbol options.' },
      { question: 'Should religious fields be mandatory?', answer: 'No. They should reflect the user’s own family practice.' },
      { question: 'Can I make the biodata in Punjabi?', answer: 'Yes. Punjabi is supported in the language-oriented builder and community pages.' },
    ],
  },
  {
    path: '/islamic-biodata-for-marriage', title: 'Islamic Biodata for Marriage | Nikah Profile', updatedAt: '2026-10-08',
    description: 'Create an Islamic biodata for marriage with optional faith, family, education, occupation and Nikah-related preferences.',
    eyebrow: 'Islamic marriage format', intro: 'An Islamic biodata for marriage can help families communicate faith, family, education and practical compatibility before a Nikah conversation. Religious terminology and expectations vary, so the profile should use the family’s own wording.',
    quickAnswer: 'A practical Islamic marriage biodata can include personal details, family, education, occupation, city, faith-related preferences where relevant, About Me, expectations and contact details. Keep religious fields accurate and optional rather than assuming one standard for every Muslim family.',
    sections: [
      { heading: 'Faith and personal details', paragraphs: ['Families may want to know about religious practice, lifestyle, sect or school of thought, or other faith-related preferences. These should be included only when the person and family actually consider them relevant.', 'Avoid making assumptions about someone’s beliefs from name, region or ethnicity. The candidate should control how their faith is described.'] },
      { heading: 'Family and education', paragraphs: ['Parents, siblings, education, occupation and current city provide practical context. For an NRI candidate, country and broad residency status can also be useful.', 'Do not publish passport, visa, identity or financial account information in a broadly shared biodata.'] },
      { heading: 'Bismillah and visual choices', paragraphs: ['The builder can support a Bismillah-style header or crescent-and-star visual treatment as an optional choice where the template supports it. The user can decide whether a religious header belongs in the final document.', 'The visual design should remain readable and respectful, with the person’s profile information taking priority.'] },
    ],
    checklist: ['Accurate faith description', 'Family and education', 'Occupation and city', 'Optional religious preferences', 'Respectful visual symbol if desired', 'Privacy-safe contact details'],
    related: [{ href: '/muslim-marriage-biodata-format', label: 'Muslim marriage biodata' }, { href: '/urdu-biodata-for-marriage', label: 'Urdu biodata' }, { href: '/marriage-biodata-format', label: 'Core format' }, { href: '/create', label: 'Create an Islamic biodata' }],
    faqs: [
      { question: 'What should an Islamic biodata for marriage include?', answer: 'Personal, family, education, occupation and expectations are a practical base, with faith-related fields added according to the person and family.' },
      { question: 'Can I include a Bismillah header?', answer: 'Yes, where the chosen template supports the optional religious-symbol system.' },
      { question: 'Should sect or school of thought be included?', answer: 'Only if it is relevant to the family’s matrimonial conversation and the person wants it stated.' },
      { question: 'Can I make the profile in Urdu?', answer: 'Yes. The language-friendly workflow can be used for Urdu-focused profiles.' },
    ],
  },,

  {
    path: '/biodata-maker-with-ganesh-photo', title: 'Biodata Maker with Ganesh Photo | Hindu Profile', updatedAt: '2026-10-08',
    description: 'Create a Hindu marriage biodata with an optional Ganeshji header, profile photo, community fields and A4 PDF or Word export.',
    eyebrow: 'Hindu visual preset', intro: 'Some Hindu families prefer a Ganeshji image or symbol at the top of a marriage biodata. The important design choice is to make that spiritual element optional and respectful while keeping the candidate’s information readable.',
    quickAnswer: 'Choose a Hindu-friendly template, select Ganeshji when it matches your family preference, add the profile photo and fill the predefined marriage fields. You can also use Om, Swastik or another available symbol when that is more appropriate to your family.',
    sections: [
      { heading: 'Religious symbols should be user-selected', paragraphs: ['A religious header is personal. The builder can suggest Ganeshji for a Hindu profile, but the user remains free to choose another supported symbol or none at all. This avoids assuming that one visual represents every Hindu household.', 'The same principle applies to Jain, Muslim, Sikh and Christian profiles: community presets can suggest a suitable starting point while the final choice remains with the person creating the biodata.'] },
      { heading: 'Keep the main photo separate from the spiritual header', paragraphs: ['The profile photograph should remain the main portrait of the candidate. A Ganeshji symbol is a decorative or cultural header element, not a replacement for the profile photo.', 'Additional candidate photos can be placed on dedicated pages so the main biodata stays clean and the spiritual header does not compete with the person’s profile.'] },
      { heading: 'Optional Hindu fields', paragraphs: ['Families may want gotra, kuldevi, devak, mosal, rashi, nakshatra or manglik status. These fields are not universal, so add only the ones the family actually uses and has verified.', 'If a family needs another term, the custom-field option can add it without changing the predefined premium structure.'] },
    ],
    checklist: ['Optional Ganeshji header', 'Profile photo', 'Verified Hindu/community fields', 'Gotra or horoscope fields only when relevant', 'Custom field option', 'A4 PDF and Word export'],
    related: [{ href: '/hindu-marriage-biodata-format', label: 'Hindu marriage biodata' }, { href: '/kundali-marriage-biodata-format', label: 'Kundali fields' }, { href: '/traditional-marriage-biodata-template', label: 'Traditional template' }, { href: '/create', label: 'Create a Hindu biodata' }],
    faqs: [
      { question: 'Can I add a Ganeshji photo or symbol?', answer: 'Yes, where the selected template supports the optional Hindu symbol preset.' },
      { question: 'Can I choose Om or Swastik instead?', answer: 'Yes. The religious-symbol system is designed to let the user choose the available symbol that fits their family preference.' },
      { question: 'Are gotra and kundali fields mandatory?', answer: 'No. They are optional and should reflect the family’s own matrimonial practice.' },
      { question: 'Can I add my own Hindu community field?', answer: 'Yes. A custom field can be added when the predefined fields do not cover a specific family requirement.' },
    ],
  },
];
