'use client';
import { useCallback, useRef, useState } from 'react';
import Cropper from 'react-easy-crop';
import { ImagePlus, X, UserRound, Check, Upload } from 'lucide-react';
import type { PhotoItem, PhotoPageMode } from '@/store/biodataStore';
function createImage(url: string) { return new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = reject; image.src = url; }); }
async function cropImage(src: string, crop: { x: number; y: number; width: number; height: number }) { const image = await createImage(src); const canvas = document.createElement('canvas'); const h = 900; canvas.width = 702; canvas.height = h; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Canvas unavailable'); ctx.drawImage(image, crop.x, crop.y, crop.width, crop.height, 0, 0, canvas.width, canvas.height); return canvas.toDataURL('image/jpeg', 0.84); }
export default function PhotoUploader({ photos, onAdd, onRemove, onSetProfile, photoPageMode, onPhotoPageModeChange }: { photos: PhotoItem[]; onAdd: (photo: PhotoItem) => void; onRemove: (id: string) => void; onSetProfile: (id: string) => void; photoPageMode: PhotoPageMode; onPhotoPageModeChange: (mode: PhotoPageMode) => void; }) {
  const input = useRef<HTMLInputElement>(null); const [source, setSource] = useState<string | null>(null); const [crop, setCrop] = useState({ x: 0, y: 0 }); const [zoom, setZoom] = useState(1); const [area, setArea] = useState<{ x:number;y:number;width:number;height:number } | null>(null); const [dragging, setDragging] = useState(false);
  const open = (files: FileList | null) => { const file = files?.[0]; if (!file || !file.type.startsWith('image/') || file.size > 10 * 1024 * 1024 || photos.length >= 5) return; const reader = new FileReader(); reader.onload = () => setSource(reader.result as string); reader.readAsDataURL(file); };
  const onCropComplete = useCallback((_: unknown, pixels: {x:number;y:number;width:number;height:number}) => setArea(pixels), []);
  const saveCrop = async () => { if (!source || !area) return; onAdd({ id: crypto.randomUUID(), dataUrl: await cropImage(source, area), name: `photo-${photos.length + 1}.jpg` }); setSource(null); setCrop({x:0,y:0}); setZoom(1); };
  const onDrop = (e: React.DragEvent) => { e.preventDefault(); setDragging(false); open(e.dataTransfer.files); };
  return <div className="space-y-4">
    <div onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={onDrop} className={`rounded-2xl border-2 border-dashed p-5 text-center ${dragging?'border-[var(--antique-gold)] bg-[#FBF7F0]':'border-stone-200 bg-white'}`}>
      <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-[#FBF7F0] text-[var(--antique-gold)]"><ImagePlus size={22}/></div><p className="text-sm font-semibold">Add your profile photo</p><p className="mt-1 text-xs text-stone-500">Portrait crop · 1 profile photo + up to 4 additional photos (5 max)</p><button type="button" className="btn-secondary mt-4" onClick={()=>input.current?.click()} disabled={photos.length>=5}><Upload size={16}/> Choose photo</button><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>open(e.target.files)}/>
    </div>
    {photos.length > 1 && <div className="rounded-2xl border border-stone-200 bg-white p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Additional photo pages</p><p className="mt-1 text-xs leading-5 text-stone-500">Profile photo stays on page 1. Choose how your other photos appear in PDF preview and printing.</p></div><select aria-label="Additional photo page layout" value={photoPageMode} onChange={e=>onPhotoPageModeChange(e.target.value as PhotoPageMode)} className="form-select !w-auto !min-h-10 !py-2 text-xs"><option value="single-per-page">One photo per page</option><option value="all-on-one-page">All photos on one page</option></select></div><p className="mt-2 text-[11px] text-stone-500">One photo per page gives each image a large, full-page presentation. All photos on one page creates a single gallery page.</p></div>}
    {photos.length>0 && <div className="grid grid-cols-3 gap-3">{photos.map((p,i)=><div key={p.id} className="group relative overflow-hidden rounded-xl border border-stone-200 bg-white p-1"><img src={p.dataUrl} alt={`Biodata photo ${i+1}`} className="aspect-[4/5] w-full rounded-lg object-cover"/>{i===0&&<span className="absolute left-2 top-2 inline-flex items-center gap-1 rounded-full bg-white/95 px-2 py-1 text-[10px] font-bold text-[var(--oxblood)] shadow"><UserRound size={11}/> Profile</span>}{i!==0&&<button type="button" onClick={()=>onSetProfile(p.id)} className="absolute bottom-2 left-2 rounded-lg bg-white/95 px-2 py-1 text-[10px] font-semibold text-stone-700 shadow">Make profile</button>}<button type="button" onClick={()=>onRemove(p.id)} className="absolute right-2 top-2 flex h-7 w-7 items-center justify-center rounded-full bg-white/95 text-stone-700 shadow" aria-label="Remove photo"><X size={14}/></button></div>)}</div>}
    {source&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-xl overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-stone-200 px-5 py-4"><div><p className="font-semibold">Crop your photo</p><p className="text-xs text-stone-500">Portrait ratio for the biodata.</p></div><button type="button" onClick={()=>setSource(null)} className="icon-button"><X size={18}/></button></div><div className="relative h-[58vh] min-h-[340px] bg-stone-950"><Cropper image={source} crop={crop} zoom={zoom} aspect={0.78} onCropChange={setCrop} onZoomChange={setZoom} onCropComplete={onCropComplete}/></div><div className="space-y-3 p-5"><label className="text-xs font-semibold text-stone-600">Zoom <input aria-label="Photo zoom" type="range" min={1} max={3} step={0.05} value={zoom} onChange={e=>setZoom(Number(e.target.value))} className="ml-3 align-middle"/></label><button type="button" className="btn-primary w-full" onClick={saveCrop}><Check size={16}/> Use this photo</button></div></div></div>}
  </div>
}
